#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Batch 2: pastContinuous, presentPerfect, pastPerfect, timeMarkers,
conditionals, passiveVoice, reportedSpeech, futureContinuous, futurePerfect
Each topic: +15 L1, +15 L2, +7 L3"""

import sys, os
sys.stdout.reconfigure(encoding='utf-8')

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXERCISES_PATH = os.path.join(BASE, 'src', 'data', 'exercises.js')

NEW = r"""
// ─── BATCH 2 EXERCISES (diffLevel 1 / 2 / 3) ────────────────────────────────

// ─── PAST CONTINUOUS ────────────────────────────────────────────────────────
exercises.pastContinuous.push(
  // Level 1 (+15)
  {id:'pc_1_01',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'I ___ watching TV when she called.',options:['was','were','am','have'],answer:'was',hint:'I = singulier → was',explanation:'"Was" avec I, he, she, it.'},
  {id:'pc_1_02',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'They ___ playing football at 5pm.',options:['was','were','are','have'],answer:'were',hint:'They = pluriel → were',explanation:'"Were" avec you, we, they.'},
  {id:'pc_1_03',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'She ___ sleeping when I arrived.',options:['was','were','is','has'],answer:'was',hint:'she = singulier → was',explanation:'"Was sleeping" = passé continu singulier.'},
  {id:'pc_1_04',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'What ___ you doing yesterday?',options:['were','was','did','have'],answer:'were',hint:'you → were',explanation:'"Were you doing?" — question passé continu.'},
  {id:'pc_1_05',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'He ___ not listening carefully.',options:['was','were','did','has'],answer:'was',hint:'he = singulier → was',explanation:'"He was not listening."'},
  {id:'pc_1_06',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'We ___ cooking dinner at 8pm.',options:['were','was','are','be'],answer:'were',hint:'we = pluriel → were',explanation:'"We were cooking."'},
  {id:'pc_1_07',type:'fill-blank',diffLevel:1,instruction:'Complétez avec was/were + -ing.',template:'It ___ raining when I left the house.',answer:'was raining',hint:'it = singulier → was',explanation:'"It was raining."'},
  {id:'pc_1_08',type:'fill-blank',diffLevel:1,instruction:'Complétez avec was/were + -ing.',template:'They ___ not working last night.',answer:'were not working',alternatives:["weren't working"],hint:'they → were',explanation:'"They were not working."'},
  {id:'pc_1_09',type:'fill-blank',diffLevel:1,instruction:'Complétez avec was/were + -ing.',template:'She ___ reading a book at midnight.',answer:'was reading',hint:'she → was',explanation:'"She was reading."'},
  {id:'pc_1_10',type:'fill-blank',diffLevel:1,instruction:'Complétez avec was/were + -ing.',template:'We ___ travelling to the capital last week.',answer:'were travelling',hint:'we → were',explanation:'"We were travelling."'},
  {id:'pc_1_11',type:'fill-blank',diffLevel:1,instruction:'Complétez avec was/were + -ing.',template:'The children ___ playing in the garden all afternoon.',answer:'were playing',hint:'children = pluriel → were',explanation:'"The children were playing."'},
  {id:'pc_1_12',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['watching','was','I','TV'],answer:'I was watching TV.',hint:'sujet + was/were + -ing',explanation:'"I was watching TV."'},
  {id:'pc_1_13',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['were','They','the','cleaning','house'],answer:'They were cleaning the house.',hint:'they → were',explanation:'"They were cleaning the house."'},
  {id:'pc_1_14',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['arrived','was','She','crying','when','he'],answer:'She was crying when he arrived.',hint:'was + -ing pour l\'action en cours',explanation:'"She was crying when he arrived."'},
  {id:'pc_1_15',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['raining','not','was','It'],answer:'It was not raining.',hint:'it → was',explanation:'"It was not raining."'},
  // Level 2 (+15)
  {id:'pc_2_01',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"J'étudiais quand le téléphone a sonné.",answer:'I was studying when the phone rang.',hint:'imparfait = past continuous',explanation:'"Was studying" = action en cours interrompue.'},
  {id:'pc_2_02',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Ils jouaient au football toute la matinée.',answer:'They were playing football all morning.',hint:'ils → were',explanation:'"They were playing."'},
  {id:'pc_2_03',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"Elle dormait quand je suis arrivé.",answer:'She was sleeping when I arrived.',hint:'elle → was',explanation:'"She was sleeping when I arrived."'},
  {id:'pc_2_04',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Que faisais-tu hier soir ?',answer:'What were you doing last night?',alternatives:['What were you doing yesterday evening?'],hint:'que faisais-tu → what were you doing',explanation:'"What were you doing...?"'},
  {id:'pc_2_05',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Nous regardions la télé pendant que tu travaillais.',answer:'We were watching TV while you were working.',hint:'pendant que = while + past continuous',explanation:'Two simultaneous past actions.'},
  {id:'pc_2_06',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'I was cooking dinner when you called.',answer:'I was cooking dinner when you called.',hint:'was + cooking',explanation:'"Was cooking" = action en cours interrompue.'},
  {id:'pc_2_07',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'They were playing in the garden all afternoon.',answer:'They were playing in the garden all afternoon.',hint:'were + playing',explanation:'"Were playing."'},
  {id:'pc_2_08',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'She was not feeling well yesterday morning.',answer:'She was not feeling well yesterday morning.',hint:'was not feeling',explanation:'"Was not feeling" = négatif passé continu.'},
  {id:'pc_2_09',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'What were you doing at seven last night?',answer:'What were you doing at seven last night?',hint:'were + doing',explanation:'"What were you doing...?"'},
  {id:'pc_2_10',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'We were travelling when it started to rain.',answer:'We were travelling when it started to rain.',hint:'were + travelling',explanation:'"Were travelling" = action en cours interrompue.'},
  {id:'pc_2_11',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['doing','were','you','What','yesterday','?'],answer:'What were you doing yesterday?',hint:'What + were + sujet + -ing',explanation:'"What were you doing yesterday?"'},
  {id:'pc_2_12',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['was','studying','She','when','arrived','I'],answer:'She was studying when I arrived.',hint:'was + studying',explanation:'"She was studying when I arrived."'},
  {id:'pc_2_13',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['were','all','They','night','working'],answer:'They were working all night.',hint:'were + working',explanation:'"They were working all night."'},
  {id:'pc_2_14',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['was','It','when','raining','we','left'],answer:'It was raining when we left.',hint:'was + raining',explanation:'"It was raining when we left."'},
  {id:'pc_2_15',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['were','listening','not','They','carefully'],answer:'They were not listening carefully.',hint:'were + not + listening',explanation:'"They were not listening carefully."'},
  // Level 3 (+7)
  {id:'pc_3_01',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'was doing',example:'I was doing my homework when my mother called.',hint:'action en cours au passé',explanation:'"Was doing" = action en cours interrompue.'},
  {id:'pc_3_02',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'were playing',example:'They were playing music when I arrived.',hint:'action simultanée dans le passé',explanation:'"Were playing" = action simultanée au passé.'},
  {id:'pc_3_03',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'He were watching TV last night.',answer:'He was watching TV last night.',hint:'he = singulier → was',explanation:'"He was watching" — singulier.'},
  {id:'pc_3_04',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'I was study when she called.',answer:'I was studying when she called.',hint:'was + verbe-ing (pas infinitif)',explanation:'"Was studying" = was + -ing.'},
  {id:'pc_3_05',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'They were talking about the exam.',answer:"Ils parlaient de l'examen.",hint:'were talking = imparfait',explanation:'"Were talking" = imparfait en français.'},
  {id:'pc_3_06',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'She was writing a letter when the power went out.',answer:"Elle écrivait une lettre quand la lumière s'est éteinte.",alternatives:["Elle rédigeait une lettre quand l'électricité a coupé."],hint:'was writing = écrivait',explanation:'"Was writing" = imparfait.'},
  {id:'pc_3_07',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'I was reading a book when my sister came in and started talking loudly.',question:'Que faisait la personne avant interruption ?',answer:'She was reading a book.',alternatives:['Reading a book.'],hint:'Écoutez la première action',explanation:'"Was reading" = action interrompue.'}
);

// ─── PRESENT PERFECT ────────────────────────────────────────────────────────
exercises.presentPerfect.push(
  // Level 1 (+15)
  {id:'pp_1_01',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'I ___ never seen snow.',options:['have','has','had','am'],answer:'have',hint:'I → have',explanation:'"I have never seen" — have + participe passé.'},
  {id:'pp_1_02',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'She ___ already eaten lunch.',options:['have','has','had','is'],answer:'has',hint:'she = singulier → has',explanation:'"She has already eaten."'},
  {id:'pp_1_03',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'We ___ just arrived.',options:['have','has','had','are'],answer:'have',hint:'we → have',explanation:'"We have just arrived."'},
  {id:'pp_1_04',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'He ___ not finished his work yet.',options:['have','has','had','did'],answer:'has',hint:'he → has',explanation:'"He has not finished yet."'},
  {id:'pp_1_05',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'They ___ lived here for ten years.',options:['have','has','had','are'],answer:'have',hint:'they → have',explanation:'"They have lived here for ten years."'},
  {id:'pp_1_06',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'___ you ever visited London?',options:['Have','Has','Did','Are'],answer:'Have',hint:'you → Have',explanation:'"Have you ever visited...?"'},
  {id:'pp_1_07',type:'fill-blank',diffLevel:1,instruction:'Complétez avec have/has.',template:'I ___ known him since 2010.',answer:'have',hint:'I → have',explanation:'"I have known him since 2010."'},
  {id:'pp_1_08',type:'fill-blank',diffLevel:1,instruction:'Complétez avec have/has.',template:'She ___ never tried sushi.',answer:'has',hint:'she → has',explanation:'"She has never tried sushi."'},
  {id:'pp_1_09',type:'fill-blank',diffLevel:1,instruction:'Complétez avec have/has.',template:'They ___ just left the office.',answer:'have',hint:'they → have',explanation:'"They have just left."'},
  {id:'pp_1_10',type:'fill-blank',diffLevel:1,instruction:'Complétez avec have/has.',template:'He ___ already done his homework.',answer:'has',hint:'he → has',explanation:'"He has already done."'},
  {id:'pp_1_11',type:'fill-blank',diffLevel:1,instruction:'Complétez avec have/has.',template:'We ___ lived here for five years.',answer:'have',hint:'we → have',explanation:'"We have lived here for five years."'},
  {id:'pp_1_12',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['ever','Have','you','been','to','Paris','?'],answer:'Have you ever been to Paris?',hint:'Have + sujet + ever + participe',explanation:'"Have you ever been to Paris?"'},
  {id:'pp_1_13',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['has','just','She','arrived'],answer:'She has just arrived.',hint:'has + just + participe',explanation:'"She has just arrived."'},
  {id:'pp_1_14',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['never','I','seen','have','that','film'],answer:'I have never seen that film.',hint:'have + never + participe',explanation:'"I have never seen that film."'},
  {id:'pp_1_15',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['finished','He','not','has','yet'],answer:'He has not finished yet.',hint:'has + not + participe + yet',explanation:'"He has not finished yet."'},
  // Level 2 (+15)
  {id:'pp_2_01',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"J'ai déjà mangé.",answer:'I have already eaten.',alternatives:["I've already eaten."],hint:'déjà → already',explanation:'"Have already eaten" — present perfect.'},
  {id:'pp_2_02',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"Elle n'a jamais vu la mer.",answer:'She has never seen the sea.',hint:'jamais → never',explanation:'"Has never seen" — present perfect négatif.'},
  {id:'pp_2_03',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Ils viennent juste d\'arriver.',answer:'They have just arrived.',alternatives:["They've just arrived."],hint:'viennent de → have just',explanation:'"Have just arrived."'},
  {id:'pp_2_04',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Tu as déjà visité Madagascar ?',answer:'Have you ever visited Madagascar?',hint:'as-tu déjà → have you ever',explanation:'"Have you ever visited...?"'},
  {id:'pp_2_05',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Nous vivons ici depuis deux ans.',answer:'We have lived here for two years.',alternatives:["We've lived here for two years."],hint:'depuis + durée → for',explanation:'"Have lived for" — present perfect + for.'},
  {id:'pp_2_06',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'I have never eaten Japanese food.',answer:'I have never eaten Japanese food.',hint:'have + never + participe',explanation:'"Have never eaten."'},
  {id:'pp_2_07',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'She has already finished her homework.',answer:'She has already finished her homework.',hint:'has + already + participe',explanation:'"Has already finished."'},
  {id:'pp_2_08',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'Have you ever met a famous person?',answer:'Have you ever met a famous person?',hint:'Have + you + ever + participe',explanation:'"Have you ever met...?"'},
  {id:'pp_2_09',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'We have lived in this city for ten years.',answer:'We have lived in this city for ten years.',hint:'have + lived + for',explanation:'"Have lived for ten years."'},
  {id:'pp_2_10',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'He has just called me.',answer:'He has just called me.',hint:'has + just + participe',explanation:'"Has just called."'},
  {id:'pp_2_11',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['ever','you','Have','eaten','sushi','?'],answer:'Have you ever eaten sushi?',hint:'Have + ever + participe',explanation:'"Have you ever eaten sushi?"'},
  {id:'pp_2_12',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['has','just','She','the','exam','passed'],answer:'She has just passed the exam.',hint:'has + just + participe',explanation:'"She has just passed the exam."'},
  {id:'pp_2_13',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['never','He','been','has','abroad'],answer:'He has never been abroad.',hint:'has + never + participe',explanation:'"He has never been abroad."'},
  {id:'pp_2_14',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['for','lived','They','years','five','here','have'],answer:'They have lived here for five years.',hint:'have + participe + for + durée',explanation:'"They have lived here for five years."'},
  {id:'pp_2_15',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['finished','has','already','She','her','work'],answer:'She has already finished her work.',hint:'has + already + participe',explanation:'"She has already finished her work."'},
  // Level 3 (+7)
  {id:'pp_3_01',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'have never',example:'I have never climbed a mountain.',hint:'"have never" + participe passé',explanation:'"Have never" = jamais fait quelque chose.'},
  {id:'pp_3_02',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'has just',example:'She has just received some great news.',hint:'"has just" + participe passé',explanation:'"Has just" = vient de faire.'},
  {id:'pp_3_03',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'I have see that movie before.',answer:'I have seen that movie before.',hint:'participe passé de see = seen',explanation:'"Have seen" — participe passé irrégulier.'},
  {id:'pp_3_04',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'She has went to Paris last year.',answer:'She went to Paris last year.',hint:'last year = passé précis → past simple',explanation:'"Last year" = date précise → past simple "went".'},
  {id:'pp_3_05',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'He has lived in France for three years.',answer:'Il vit en France depuis trois ans.',hint:'for = depuis + durée',explanation:'Present perfect + for = "depuis" en français.'},
  {id:'pp_3_06',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'Have they arrived yet?',answer:'Sont-ils déjà arrivés ?',alternatives:['Ont-ils déjà arrive ?'],hint:'Have they...? = Sont-ils...?',explanation:'"Have they arrived yet?" = "Sont-ils déjà arrivés?"'},
  {id:'pp_3_07',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'I have visited five countries but I have never been to Asia.',question:"A-t-il visité l'Asie ?",answer:'No, he has never been to Asia.',alternatives:['No.','Never.'],hint:'Écoutez "never"',explanation:'"Has never been to Asia" = jamais visité l\'Asie.'}
);

// ─── PAST PERFECT ───────────────────────────────────────────────────────────
exercises.pastPerfect.push(
  // Level 1 (+15)
  {id:'ppt_1_01',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'By the time I arrived, she ___ already left.',options:['had','have','was','did'],answer:'had',hint:'avant un autre passé → had',explanation:'"Had left" = action avant une autre action passée.'},
  {id:'ppt_1_02',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'He ___ never eaten sushi before that day.',options:['had','have','was','did'],answer:'had',hint:'before → had + participe',explanation:'"Had never eaten" avant ce moment.'},
  {id:'ppt_1_03',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'They ___ finished the work before I called.',options:['had','have','were','did'],answer:'had',hint:'before → past perfect',explanation:'"Had finished" avant l\'appel.'},
  {id:'ppt_1_04',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'We ___ just started when it began to rain.',options:['had','have','was','were'],answer:'had',hint:'just → had just',explanation:'"Had just started."'},
  {id:'ppt_1_05',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'She ___ not met him before the party.',options:['had','have','was','did'],answer:'had',hint:'before = avant → past perfect',explanation:'"Had not met" = ne l\'avait pas rencontré.'},
  {id:'ppt_1_06',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'___ you visited Paris before 2020?',options:['Had','Have','Did','Were'],answer:'Had',hint:'Question past perfect = Had + sujet?',explanation:'"Had you visited...?" = question past perfect.'},
  {id:'ppt_1_07',type:'fill-blank',diffLevel:1,instruction:'Complétez avec had + participe.',template:'By 8pm, I ___ already eaten.',answer:'had already eaten',hint:'had + already + participe',explanation:'"Had already eaten."'},
  {id:'ppt_1_08',type:'fill-blank',diffLevel:1,instruction:'Complétez avec had + participe.',template:'She ___ never seen such a big city.',answer:'had never seen',hint:'had + never + participe',explanation:'"Had never seen."'},
  {id:'ppt_1_09',type:'fill-blank',diffLevel:1,instruction:'Complétez avec had + participe.',template:'He ___ finished the book before the exam.',answer:'had finished',hint:'before → past perfect',explanation:'"Had finished before."'},
  {id:'ppt_1_10',type:'fill-blank',diffLevel:1,instruction:'Complétez avec had + participe.',template:'They ___ left by the time we arrived.',answer:'had left',hint:'by the time → past perfect',explanation:'"Had left" avant notre arrivée.'},
  {id:'ppt_1_11',type:'fill-blank',diffLevel:1,instruction:'Complétez avec had + participe.',template:'I ___ never heard that song before.',answer:'had never heard',hint:'never before → past perfect',explanation:'"Had never heard."'},
  {id:'ppt_1_12',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['arrived','By','I','she','the','had','left','time'],answer:'By the time I arrived, she had left.',hint:'By the time + past simple, had + participe',explanation:'"By the time I arrived, she had left."'},
  {id:'ppt_1_13',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['already','eaten','had','He','dinner'],answer:'He had already eaten dinner.',hint:'had + already + participe',explanation:'"He had already eaten dinner."'},
  {id:'ppt_1_14',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['not','We','had','met','before'],answer:'We had not met before.',hint:'had + not + participe',explanation:'"We had not met before."'},
  {id:'ppt_1_15',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['finished','Had','she','her','work','?'],answer:'Had she finished her work?',hint:'Had + sujet + participe?',explanation:'"Had she finished her work?"'},
  // Level 2 (+15)
  {id:'ppt_2_01',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"Quand je suis arrivé, elle était déjà partie.",answer:'When I arrived, she had already left.',hint:'elle était partie → she had left',explanation:'"Had left" = plus-que-parfait.'},
  {id:'ppt_2_02',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"Il n'avait jamais vu la mer avant ce voyage.",answer:'He had never seen the sea before that trip.',hint:'il n\'avait jamais → he had never',explanation:'"Had never seen" = jamais vu avant ce moment.'},
  {id:'ppt_2_03',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Ils avaient fini leur travail avant la réunion.',answer:'They had finished their work before the meeting.',hint:'ils avaient fini → they had finished',explanation:'"Had finished before the meeting."'},
  {id:'ppt_2_04',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Avais-tu déjà visité Paris avant cette fois ?',answer:'Had you visited Paris before that time?',alternatives:['Had you been to Paris before?'],hint:'avais-tu → had you',explanation:'"Had you visited...?"'},
  {id:'ppt_2_05',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"Nous venions juste de commencer quand il a plu.",answer:'We had just started when it rained.',hint:'nous venions de → we had just',explanation:'"Had just started when it rained."'},
  {id:'ppt_2_06',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'She had already eaten when I arrived.',answer:'She had already eaten when I arrived.',hint:'had + already + participe',explanation:'"Had already eaten."'},
  {id:'ppt_2_07',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'Had you met him before the party?',answer:'Had you met him before the party?',hint:'Had + sujet + participe?',explanation:'"Had you met him before the party?"'},
  {id:'ppt_2_08',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'They had not finished the project by Friday.',answer:'They had not finished the project by Friday.',hint:'had + not + participe',explanation:'"Had not finished by Friday."'},
  {id:'ppt_2_09',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'He had never tried coffee before that day.',answer:'He had never tried coffee before that day.',hint:'had + never + participe',explanation:'"Had never tried."'},
  {id:'ppt_2_10',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'By the time we arrived the film had started.',answer:'By the time we arrived the film had started.',hint:'by the time → past perfect',explanation:'"Had started" avant notre arrivée.'},
  {id:'ppt_2_11',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['arrived','she','By','the','time','had','I','left'],answer:'By the time I arrived, she had left.',hint:'By the time + past simple, had + participe',explanation:'"By the time I arrived, she had left."'},
  {id:'ppt_2_12',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['never','He','had','flown','before'],answer:'He had never flown before.',hint:'had + never + participe',explanation:'"He had never flown before."'},
  {id:'ppt_2_13',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['already','started','Had','the','film','?'],answer:'Had the film already started?',hint:'Had + sujet + already + participe?',explanation:'"Had the film already started?"'},
  {id:'ppt_2_14',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['finished','had','They','eating','when','arrived','we'],answer:'They had finished eating when we arrived.',hint:'had + participe + when',explanation:'"They had finished eating when we arrived."'},
  {id:'ppt_2_15',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['not','had','the','We','key','forgotten'],answer:'We had not forgotten the key.',hint:'had + not + participe',explanation:'"We had not forgotten the key."'},
  // Level 3 (+7)
  {id:'ppt_3_01',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'had already',example:'She had already left when I called.',hint:'"had already" + participe passé',explanation:'"Had already" = déjà fait avant un autre passé.'},
  {id:'ppt_3_02',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'had never',example:'He had never seen such a beautiful place.',hint:'"had never" + participe passé',explanation:'"Had never" = jamais fait avant ce moment.'},
  {id:'ppt_3_03',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'I have seen that film before you arrived.',answer:'I had seen that film before you arrived.',hint:'avant un passé → had, pas have',explanation:'"Had seen" — past perfect, pas present perfect.'},
  {id:'ppt_3_04',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'She had went to Paris before the trip.',answer:'She had gone to Paris before the trip.',hint:'participe passé de go = gone',explanation:'"Had gone" — participe irrégulier.'},
  {id:'ppt_3_05',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'We had finished dinner before they arrived.',answer:"Nous avions fini le dîner avant leur arrivée.",hint:'had finished = avions fini',explanation:'"Had finished" = plus-que-parfait.'},
  {id:'ppt_3_06',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'He had already spoken to her.',answer:'Il lui avait déjà parlé.',hint:'had spoken = avait parlé',explanation:'"Had spoken" = plus-que-parfait.'},
  {id:'ppt_3_07',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'By the time the ambulance arrived the doctor had already treated the patient.',question:'Qui avait traité le patient en premier ?',answer:'The doctor had already treated the patient.',alternatives:['The doctor.'],hint:'Écoutez "had already"',explanation:'"Had already treated" = action avant l\'ambulance.'}
);

// ─── TIME MARKERS ───────────────────────────────────────────────────────────
exercises.timeMarkers.push(
  // Level 1 (+15)
  {id:'tm_1_01',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon marqueur temporel.',question:'I have ___ finished my homework.',options:['already','yet','since','for'],answer:'already',hint:'action complète avant maintenant → already',explanation:'"Already" = déjà (action déjà faite).'},
  {id:'tm_1_02',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon marqueur temporel.',question:'Have you eaten lunch ___?',options:['already','yet','since','for'],answer:'yet',hint:'question ou négatif → yet',explanation:'"Yet" = encore/déjà (dans questions et négatifs).'},
  {id:'tm_1_03',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon marqueur temporel.',question:'She ___ lives here — she has not moved.',options:['already','yet','still','just'],answer:'still',hint:'situation qui continue → still',explanation:'"Still" = toujours (situation continue).'},
  {id:'tm_1_04',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon marqueur temporel.',question:'He left ten minutes ___.',options:['ago','since','for','yet'],answer:'ago',hint:'durée + ago = il y a ...',explanation:'"Ago" = il y a (passé simple).'},
  {id:'tm_1_05',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon marqueur temporel.',question:'She has been sick ___ Monday.',options:['since','for','ago','yet'],answer:'since',hint:'point de départ précis → since',explanation:'"Since" = depuis un moment précis.'},
  {id:'tm_1_06',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon marqueur temporel.',question:'We have been waiting ___ two hours.',options:['since','for','ago','yet'],answer:'for',hint:'durée → for',explanation:'"For" = depuis une durée.'},
  {id:'tm_1_07',type:'fill-blank',diffLevel:1,instruction:'Complétez avec le bon marqueur.',template:'I have ___ arrived — I am at the door.',answer:'just',hint:'vient de se passer → just',explanation:'"Just" = vient de (action très récente).'},
  {id:'tm_1_08',type:'fill-blank',diffLevel:1,instruction:'Complétez avec yet ou already.',template:'Have you finished ___?',answer:'yet',hint:'question → yet',explanation:'"Yet" dans les questions = déjà?'},
  {id:'tm_1_09',type:'fill-blank',diffLevel:1,instruction:'Complétez avec still ou yet.',template:'She ___ studies every night.',answer:'still',hint:'habitude continue → still',explanation:'"Still" = toujours, continue à.'},
  {id:'tm_1_10',type:'fill-blank',diffLevel:1,instruction:'Complétez avec ago ou since.',template:'He left ten minutes ___.',answer:'ago',hint:'durée + ago = il y a',explanation:'"Ten minutes ago" = il y a dix minutes.'},
  {id:'tm_1_11',type:'fill-blank',diffLevel:1,instruction:'Complétez avec for ou since.',template:'They have known each other ___ 2015.',answer:'since',hint:'point de départ → since',explanation:'"Since 2015" = depuis 2015 (point précis).'},
  {id:'tm_1_12',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['already','have','finished','I'],answer:'I have already finished.',hint:'have + already + participe',explanation:'"Already" entre have et le participe.'},
  {id:'tm_1_13',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['yet','you','Have','eaten','?'],answer:'Have you eaten yet?',hint:'yet en fin de phrase → question',explanation:'"Have you eaten yet?" = tu as déjà mangé?'},
  {id:'tm_1_14',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['been','waiting','We','since','have','morning'],answer:'We have been waiting since morning.',hint:'have been + -ing + since',explanation:'"Since morning" = depuis ce matin.'},
  {id:'tm_1_15',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['arrived','just','He','has'],answer:'He has just arrived.',hint:'has + just + participe',explanation:'"He has just arrived."'},
  // Level 2 (+15)
  {id:'tm_2_01',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Je viens de finir mes devoirs.',answer:'I have just finished my homework.',alternatives:["I've just finished my homework."],hint:'viens de → have just',explanation:'"Just" = vient de faire.'},
  {id:'tm_2_02',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'As-tu déjà mangé ?',answer:'Have you eaten yet?',alternatives:['Have you already eaten?'],hint:'déjà (question) → yet / already',explanation:'"Have you eaten yet?"'},
  {id:'tm_2_03',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"Elle habite ici depuis 2010.",answer:'She has lived here since 2010.',hint:'depuis + date → since',explanation:'"Since 2010" = depuis 2010.'},
  {id:'tm_2_04',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"Il y a dix ans, j'étais à l'école.",answer:'Ten years ago, I was at school.',hint:'il y a → ago + past simple',explanation:'"Ago" + past simple = il y a.'},
  {id:'tm_2_05',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Il travaille ici depuis cinq ans.',answer:'He has worked here for five years.',alternatives:["He's worked here for five years."],hint:'depuis + durée → for',explanation:'"For five years" = depuis cinq ans (durée).'},
  {id:'tm_2_06',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'I have already seen that film.',answer:'I have already seen that film.',hint:'already entre have et participe',explanation:'"Have already seen."'},
  {id:'tm_2_07',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'She has been ill since Monday.',answer:'She has been ill since Monday.',hint:'since + point précis',explanation:'"Since Monday."'},
  {id:'tm_2_08',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'Have you finished your work yet?',answer:'Have you finished your work yet?',hint:'yet en fin',explanation:'"Have you finished yet?"'},
  {id:'tm_2_09',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'He left ten minutes ago.',answer:'He left ten minutes ago.',hint:'ago + past simple',explanation:'"Ten minutes ago."'},
  {id:'tm_2_10',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'They have lived here for three years.',answer:'They have lived here for three years.',hint:'for + durée',explanation:'"For three years."'},
  {id:'tm_2_11',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['ten','ago','years','He','was','born'],answer:'He was born ten years ago.',hint:'durée + ago + past simple',explanation:'"Ten years ago."'},
  {id:'tm_2_12',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['yet','not','have','finished','I'],answer:'I have not finished yet.',hint:'yet en fin, négatif',explanation:'"I have not finished yet."'},
  {id:'tm_2_13',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['since','have','We','known','each','other','2018'],answer:'We have known each other since 2018.',hint:'since + date',explanation:'"Since 2018."'},
  {id:'tm_2_14',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['still','working','She','is'],answer:'She is still working.',hint:'still entre is et le verbe',explanation:'"Still working" = toujours en train de travailler.'},
  {id:'tm_2_15',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['just','arrived','has','He'],answer:'He has just arrived.',hint:'has + just + participe',explanation:'"He has just arrived."'},
  // Level 3 (+7)
  {id:'tm_3_01',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'since',example:'She has been a teacher since 2015.',hint:'"since" + moment précis',explanation:'"Since" = depuis un point précis dans le temps.'},
  {id:'tm_3_02',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'already',example:'I have already read that book twice.',hint:'"already" entre have et le participe',explanation:'"Already" = déjà accompli.'},
  {id:'tm_3_03',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'I have been waiting since two hours.',answer:'I have been waiting for two hours.',hint:'durée → for, pas since',explanation:'"For" + durée. "Since" + point précis.'},
  {id:'tm_3_04',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'She has left already ten minutes ago.',answer:'She left ten minutes ago.',hint:'"ago" = past simple, pas present perfect',explanation:'"Ago" avec le past simple uniquement.'},
  {id:'tm_3_05',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'He has been studying English for three years.',answer:"Il étudie l'anglais depuis trois ans.",hint:'for = depuis + durée',explanation:'Present perfect + for = "depuis" en français.'},
  {id:'tm_3_06',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'Have they arrived yet?',answer:'Sont-ils déjà arrivés ?',hint:'Have they...yet? = Sont-ils déjà...?',explanation:'"Yet" dans les questions = "déjà" en français.'},
  {id:'tm_3_07',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'I have known her since we were children but I have not seen her for two years.',question:'Depuis combien de temps ne se sont-ils pas vus ?',answer:'For two years.',alternatives:['Two years.'],hint:'Écoutez "for"',explanation:'"For two years" = depuis deux ans.'}
);

// ─── CONDITIONALS ──────────────────────────────────────────────────────────
exercises.conditionals.push(
  // Level 1 (+15)
  {id:'cond_1_01',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'If you heat water to 100°C, it ___.',options:['boils','will boil','would boil','boiled'],answer:'boils',hint:'vérité générale → present simple',explanation:'Conditionnel 0 : If + présent, présent.'},
  {id:'cond_1_02',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'If it rains tomorrow, I ___ stay home.',options:['will','would','should','am'],answer:'will',hint:'futur probable → will',explanation:'Conditionnel 1 : If + présent, will + infinitif.'},
  {id:'cond_1_03',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'If I were rich, I ___ travel the world.',options:['will','would','should','could'],answer:'would',hint:'situation irréelle → would',explanation:'Conditionnel 2 : If + past, would + infinitif.'},
  {id:'cond_1_04',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'If she ___ harder, she would pass.',options:['studied','studies','will study','had studied'],answer:'studied',hint:'conditionnel 2 → past simple',explanation:'Conditionnel 2 : "If she studied..."'},
  {id:'cond_1_05',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'If I had known, I ___ told you.',options:['would have','will have','would','had'],answer:'would have',hint:'passé irréel → would have',explanation:'Conditionnel 3 : would have + participe.'},
  {id:'cond_1_06',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'If they leave now, they ___ on time.',options:['will be','would be','are','were'],answer:'will be',hint:'futur probable → will',explanation:'Conditionnel 1 : "If they leave, they will be."'},
  {id:'cond_1_07',type:'fill-blank',diffLevel:1,instruction:'Complétez la phrase.',template:'If you study, you ___ pass the exam.',answer:'will',hint:'conditionnel 1 → will',explanation:'"Will pass" — condition réalisable.'},
  {id:'cond_1_08',type:'fill-blank',diffLevel:1,instruction:'Complétez la phrase.',template:'If I ___ a bird, I would fly.',answer:'were',hint:'conditionnel 2 → were (pour toutes personnes)',explanation:'"If I were" — subjonctif conditionnel 2.'},
  {id:'cond_1_09',type:'fill-blank',diffLevel:1,instruction:'Complétez la phrase.',template:'If it snows, the school ___ close.',answer:'will',hint:'condition probable → will',explanation:'"Will close" — conditionnel 1.'},
  {id:'cond_1_10',type:'fill-blank',diffLevel:1,instruction:'Complétez la phrase.',template:'If he had called, I ___ answered.',answer:'would have',hint:'passé irréel → would have',explanation:'"Would have answered" — conditionnel 3.'},
  {id:'cond_1_11',type:'fill-blank',diffLevel:1,instruction:'Complétez la phrase.',template:'She ___ help if she could.',answer:'would',hint:'conditionnel 2 → would',explanation:'"Would help" — conditionnel 2.'},
  {id:'cond_1_12',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['it','stay','I','home','will','rains','If'],answer:'If it rains, I will stay home.',hint:'If + présent, will + infinitif',explanation:'Conditionnel 1.'},
  {id:'cond_1_13',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['were','I','fly','rich','would','I','if'],answer:'If I were rich, I would fly.',hint:'If + were, would + infinitif',explanation:'Conditionnel 2 — hypothèse irréelle.'},
  {id:'cond_1_14',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['studied','if','he','pass','would','harder','He'],answer:'If he studied harder, he would pass.',hint:'conditionnel 2',explanation:'Conditionnel 2.'},
  {id:'cond_1_15',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['had','known','would','If','she','have','told','him'],answer:'If she had known, she would have told him.',hint:'conditionnel 3',explanation:'Conditionnel 3 — passé irréel.'},
  // Level 2 (+15)
  {id:'cond_2_01',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"Si tu étudies, tu réussiras l'examen.",answer:'If you study, you will pass the exam.',hint:'conditionnel 1 → will',explanation:'Conditionnel 1.'},
  {id:'cond_2_02',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"Si j'étais riche, j'achèterais une maison.",answer:'If I were rich, I would buy a house.',hint:'conditionnel 2 → would',explanation:'Conditionnel 2 — hypothèse irréelle.'},
  {id:'cond_2_03',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"Si elle avait su, elle serait venue.",answer:'If she had known, she would have come.',hint:'conditionnel 3 → would have',explanation:'Conditionnel 3 — passé irréel.'},
  {id:'cond_2_04',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Si tu as faim, mange quelque chose.',answer:'If you are hungry, eat something.',hint:'conditionnel 0 → présent',explanation:'Conditionnel 0 — vérité générale / conseil.'},
  {id:'cond_2_05',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"Si nous partions maintenant, nous arriverions à l'heure.",answer:'If we left now, we would arrive on time.',alternatives:['If we left now, we would be on time.'],hint:'conditionnel 2 → would',explanation:'Conditionnel 2.'},
  {id:'cond_2_06',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'If it rains tomorrow we will cancel the trip.',answer:'If it rains tomorrow we will cancel the trip.',hint:'conditionnel 1',explanation:'"Will cancel" — conditionnel 1.'},
  {id:'cond_2_07',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'If I were you I would apologise.',answer:'If I were you I would apologise.',hint:'conditionnel 2',explanation:'"Would apologise" — conditionnel 2.'},
  {id:'cond_2_08',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'If she had worked harder she would have passed.',answer:'If she had worked harder she would have passed.',hint:'conditionnel 3',explanation:'"Would have passed" — conditionnel 3.'},
  {id:'cond_2_09',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'What would you do if you won the lottery?',answer:'What would you do if you won the lottery?',hint:'conditionnel 2',explanation:'"Would do" — conditionnel 2.'},
  {id:'cond_2_10',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'If you heat ice it melts.',answer:'If you heat ice it melts.',hint:'conditionnel 0',explanation:'"Melts" — vérité générale, conditionnel 0.'},
  {id:'cond_2_11',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['you','would','do','If','what','won','lottery','the'],answer:'What would you do if you won the lottery?',hint:'conditionnel 2 — question',explanation:'Question au conditionnel 2.'},
  {id:'cond_2_12',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['will','If','study','you','you','pass'],answer:'If you study, you will pass.',hint:'conditionnel 1',explanation:'Conditionnel 1.'},
  {id:'cond_2_13',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['have','I','told','had','you','known','If','would'],answer:'If I had known, I would have told you.',hint:'conditionnel 3',explanation:'Conditionnel 3.'},
  {id:'cond_2_14',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['help','him','I','could','if','would'],answer:'I would help him if I could.',hint:'conditionnel 2',explanation:'"I would help him if I could."'},
  {id:'cond_2_15',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['she','If','came','be','happy','would','I'],answer:'If she came, I would be happy.',hint:'conditionnel 2',explanation:'Conditionnel 2.'},
  // Level 3 (+7)
  {id:'cond_3_01',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'If I were',example:'If I were the president, I would build more schools.',hint:'conditionnel 2 — hypothèse irréelle',explanation:'"If I were" = conditionnel 2 (situation imaginaire).'},
  {id:'cond_3_02',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'If I had known',example:'If I had known the truth, I would not have lied.',hint:'conditionnel 3 — passé irréel',explanation:'"If I had known" = conditionnel 3.'},
  {id:'cond_3_03',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'If I will study harder, I will pass.',answer:'If I study harder, I will pass.',hint:'pas de "will" dans la clause if (cond. 1)',explanation:'Conditionnel 1 : "If + présent simple, will..."'},
  {id:'cond_3_04',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'If she would have known, she would have helped.',answer:'If she had known, she would have helped.',hint:'cond. 3 : if + had + participe',explanation:'Conditionnel 3 : "If + had + participe."'},
  {id:'cond_3_05',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'If it rains, the match will be cancelled.',answer:'Si il pleut, le match sera annulé.',alternatives:["S'il pleut, le match sera annulé."],hint:'conditionnel 1 → futur',explanation:'Conditionnel 1 : futur en français.'},
  {id:'cond_3_06',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'She would travel more if she had money.',answer:'Elle voyagerait davantage si elle avait de l\'argent.',hint:'conditionnel 2 → conditionnel présent',explanation:'Conditionnel 2 en français.'},
  {id:'cond_3_07',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'If you exercise every day you will feel better. If I were younger I would run a marathon.',question:'Quel type de conditionnel est la deuxième phrase ?',answer:'Type 2 (second conditional).',alternatives:['Conditional 2.','Second conditional.'],hint:'were + would = conditionnel 2',explanation:'"If I were younger" = conditionnel 2, hypothèse irréelle.'}
);

// ─── PASSIVE VOICE ──────────────────────────────────────────────────────────
exercises.passiveVoice.push(
  // Level 1 (+15)
  {id:'pv_1_01',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'The book ___ written by Shakespeare.',options:['was','is','were','be'],answer:'was',hint:'passé singulier → was',explanation:'Passif passé singulier : was + participe.'},
  {id:'pv_1_02',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'The letters ___ sent every morning.',options:['is','are','was','were'],answer:'are',hint:'pluriel présent → are',explanation:'Passif présent pluriel : are + participe.'},
  {id:'pv_1_03',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'The car ___ stolen last night.',options:['is','are','was','were'],answer:'was',hint:'passé singulier → was',explanation:'Passif passé : was + participe.'},
  {id:'pv_1_04',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'English ___ spoken all over the world.',options:['is','are','was','were'],answer:'is',hint:'présent singulier → is',explanation:'Passif présent singulier : is + participe.'},
  {id:'pv_1_05',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'The cakes ___ made by my mother.',options:['was','were','is','are'],answer:'were',hint:'passé pluriel → were',explanation:'Passif passé pluriel : were + participe.'},
  {id:'pv_1_06',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'This photo ___ taken in 2010.',options:['is','are','was','were'],answer:'was',hint:'passé singulier → was',explanation:'Passif passé singulier.'},
  {id:'pv_1_07',type:'fill-blank',diffLevel:1,instruction:'Complétez avec is/are/was/were.',template:'Rice ___ grown in Madagascar.',answer:'is',hint:'présent singulier → is',explanation:'"Rice is grown" — passif présent.'},
  {id:'pv_1_08',type:'fill-blank',diffLevel:1,instruction:'Complétez avec is/are/was/were.',template:'Many trees ___ cut down every year.',answer:'are',hint:'trees = pluriel → are',explanation:'"Trees are cut down" — passif pluriel.'},
  {id:'pv_1_09',type:'fill-blank',diffLevel:1,instruction:'Complétez avec is/are/was/were.',template:'The bridge ___ built in 1900.',answer:'was',hint:'passé singulier → was',explanation:'"Was built" — passé passif.'},
  {id:'pv_1_10',type:'fill-blank',diffLevel:1,instruction:'Complétez avec is/are/was/were.',template:'The film ___ directed by Spielberg.',answer:'was',hint:'passé singulier → was',explanation:'"Was directed" — passif passé.'},
  {id:'pv_1_11',type:'fill-blank',diffLevel:1,instruction:'Complétez avec is/are/was/were.',template:'These shoes ___ made in Italy.',answer:'are',hint:'shoes = pluriel → are',explanation:'"Shoes are made" — passif présent pluriel.'},
  {id:'pv_1_12',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['was','car','stolen','The'],answer:'The car was stolen.',hint:'sujet + was/were + participe',explanation:'"The car was stolen" — passif passé.'},
  {id:'pv_1_13',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['are','English','world','over','spoken','the','all','and','French'],answer:'English and French are spoken all over the world.',hint:'are + participe',explanation:'Passif présent pluriel.'},
  {id:'pv_1_14',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['was','The','built','1990','in','school'],answer:'The school was built in 1990.',hint:'was + participe',explanation:'"The school was built in 1990."'},
  {id:'pv_1_15',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['letter','sent','been','The','has'],answer:'The letter has been sent.',hint:'has + been + participe (present perfect passif)',explanation:'"Has been sent" — passif present perfect.'},
  // Level 2 (+15)
  {id:'pv_2_01',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'La voiture a été volée hier soir.',answer:'The car was stolen last night.',hint:'a été volée → was stolen',explanation:'Passif passé.'},
  {id:'pv_2_02',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Le riz est cultivé dans de nombreux pays.',answer:'Rice is grown in many countries.',hint:'est cultivé → is grown',explanation:'Passif présent.'},
  {id:'pv_2_03',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Ce livre a été écrit par un auteur célèbre.',answer:'This book was written by a famous author.',hint:'a été écrit → was written',explanation:'Passif passé + by.'},
  {id:'pv_2_04',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"L'école sera construite l'année prochaine.",answer:'The school will be built next year.',hint:'sera construite → will be built',explanation:'Passif futur : will be + participe.'},
  {id:'pv_2_05',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Les fenêtres ont été cassées par le vent.',answer:'The windows were broken by the wind.',hint:'ont été cassées → were broken',explanation:'Passif passé pluriel.'},
  {id:'pv_2_06',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'The letter was sent this morning.',answer:'The letter was sent this morning.',hint:'was + participe',explanation:'Passif passé.'},
  {id:'pv_2_07',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'English is spoken in many countries.',answer:'English is spoken in many countries.',hint:'is + participe',explanation:'Passif présent.'},
  {id:'pv_2_08',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'The bridge was built over a hundred years ago.',answer:'The bridge was built over a hundred years ago.',hint:'was + participe',explanation:'Passif passé + ago.'},
  {id:'pv_2_09',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'The match was cancelled because of the rain.',answer:'The match was cancelled because of the rain.',hint:'was + participe',explanation:'Passif passé.'},
  {id:'pv_2_10',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'A new hospital is being built in the city.',answer:'A new hospital is being built in the city.',hint:'is being + participe = passif présent continu',explanation:'"Is being built" — passif présent continu.'},
  {id:'pv_2_11',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['was','discovered','America','by','Columbus'],answer:'America was discovered by Columbus.',hint:'sujet + was + participe + by',explanation:'"America was discovered by Columbus."'},
  {id:'pv_2_12',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['is','French','Madagascar','spoken','in'],answer:'French is spoken in Madagascar.',hint:'is + participe',explanation:'"French is spoken in Madagascar."'},
  {id:'pv_2_13',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['damaged','was','storm','The','house','in','the'],answer:'The house was damaged in the storm.',hint:'was + participe',explanation:'"The house was damaged in the storm."'},
  {id:'pv_2_14',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['will','be','The','tomorrow','finished','work'],answer:'The work will be finished tomorrow.',hint:'will + be + participe',explanation:'Passif futur.'},
  {id:'pv_2_15',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['been','The','stolen','has','bicycle'],answer:'The bicycle has been stolen.',hint:'has + been + participe',explanation:'Passif present perfect.'},
  // Level 3 (+7)
  {id:'pv_3_01',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'was built',example:'The Eiffel Tower was built in 1889.',hint:'was + participe passé',explanation:'Passif passé pour décrire une construction.'},
  {id:'pv_3_02',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'is spoken',example:'English is spoken by millions of people.',hint:'is + participe passé',explanation:'Passif présent pour une vérité générale.'},
  {id:'pv_3_03',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'The book was wrote by Tolstoy.',answer:'The book was written by Tolstoy.',hint:'participe de write = written',explanation:'"Written" = participe passé de "write".'},
  {id:'pv_3_04',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'English is speak in many countries.',answer:'English is spoken in many countries.',hint:'passif = is + participe',explanation:'"Is spoken" — participe passif.'},
  {id:'pv_3_05',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'The road is being repaired.',answer:'La route est en train d\'être réparée.',alternatives:['On répare la route.'],hint:'is being repaired = en cours',explanation:'Passif présent continu.'},
  {id:'pv_3_06',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'The criminal was caught by the police.',answer:'Le criminel a été arrêté par la police.',hint:'was caught = a été arrêté',explanation:'Passif passé en français.'},
  {id:'pv_3_07',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'The Mona Lisa was painted by Leonardo da Vinci and is kept in the Louvre Museum in Paris.',question:'Par qui la Joconde a-t-elle été peinte ?',answer:'By Leonardo da Vinci.',alternatives:['Leonardo da Vinci.'],hint:'Écoutez "painted by"',explanation:'"Was painted by Leonardo da Vinci."'}
);

// ─── REPORTED SPEECH ────────────────────────────────────────────────────────
exercises.reportedSpeech.push(
  // Level 1 (+15)
  {id:'rs_1_01',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'"I am tired." → He said he ___ tired.',options:['was','is','were','be'],answer:'was',hint:'am → was (backshifting)',explanation:'"Am" devient "was" au discours indirect.'},
  {id:'rs_1_02',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'"I will help." → She said she ___ help.',options:['would','will','could','should'],answer:'would',hint:'will → would',explanation:'"Will" devient "would" au discours indirect.'},
  {id:'rs_1_03',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'"I can swim." → She said she ___ swim.',options:['could','can','would','should'],answer:'could',hint:'can → could',explanation:'"Can" devient "could" au discours indirect.'},
  {id:'rs_1_04',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'"I ate lunch." → He said he ___ eaten lunch.',options:['had','has','have','did'],answer:'had',hint:'past simple → past perfect',explanation:'Past simple devient past perfect au discours indirect.'},
  {id:'rs_1_05',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'"Do you like coffee?" → He asked if I ___ coffee.',options:['liked','like','liking','likes'],answer:'liked',hint:'present simple → past simple',explanation:'"Like" devient "liked" au discours indirect.'},
  {id:'rs_1_06',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'"Where do you live?" → She asked where I ___.',options:['lived','live','living','lives'],answer:'lived',hint:'présent → passé',explanation:'"Live" devient "lived" au discours indirect.'},
  {id:'rs_1_07',type:'fill-blank',diffLevel:1,instruction:'Transformez au discours indirect.',template:'"I am happy." → She said she ___ happy.',answer:'was',hint:'am → was',explanation:'"Am" → "was" (backshifting).'},
  {id:'rs_1_08',type:'fill-blank',diffLevel:1,instruction:'Transformez au discours indirect.',template:'"I will call you." → He said he ___ call me.',answer:'would',hint:'will → would',explanation:'"Will" → "would".'},
  {id:'rs_1_09',type:'fill-blank',diffLevel:1,instruction:'Transformez au discours indirect.',template:'"I can drive." → She said she ___ drive.',answer:'could',hint:'can → could',explanation:'"Can" → "could".'},
  {id:'rs_1_10',type:'fill-blank',diffLevel:1,instruction:'Transformez au discours indirect.',template:'"I have finished." → He said he ___ finished.',answer:'had',hint:'present perfect → past perfect',explanation:'"Have finished" → "had finished".'},
  {id:'rs_1_11',type:'fill-blank',diffLevel:1,instruction:'Transformez au discours indirect.',template:'"I like music." → She said she ___ music.',answer:'liked',hint:'like → liked',explanation:'"Like" → "liked".'},
  {id:'rs_1_12',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['said','tired','she','She','was'],answer:'She said she was tired.',hint:'said + she + was',explanation:'Discours indirect : said (that) she was.'},
  {id:'rs_1_13',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['asked','I','liked','he','if','coffee'],answer:'He asked if I liked coffee.',hint:'asked + if + sujet + passé',explanation:'Question indirecte : asked if I liked.'},
  {id:'rs_1_14',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['said','would','She','me','she','help'],answer:'She said she would help me.',hint:'said + she + would',explanation:'"Will" → "would" au discours indirect.'},
  {id:'rs_1_15',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['where','asked','He','I','lived'],answer:'He asked where I lived.',hint:'asked + where + sujet + passé',explanation:'Question indirecte avec "where".'},
  // Level 2 (+15)
  {id:'rs_2_01',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'"Je suis fatigué," dit-il.',answer:'He said he was tired.',alternatives:['He said that he was tired.'],hint:'il dit → he said + he was',explanation:'Am → was (backshifting).'},
  {id:'rs_2_02',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'"J\'irai à Paris," dit-elle.',answer:'She said she would go to Paris.',alternatives:['She said that she would go to Paris.'],hint:'will → would',explanation:'"Will go" → "would go".'},
  {id:'rs_2_03',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'"Je peux nager," dit-il.',answer:'He said he could swim.',hint:'can → could',explanation:'"Can swim" → "could swim".'},
  {id:'rs_2_04',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'"Aimes-tu le café ?" demanda-t-il.',answer:'He asked if I liked coffee.',alternatives:['He asked whether I liked coffee.'],hint:'demanda si → asked if',explanation:'Question indirecte : asked if + past simple.'},
  {id:'rs_2_05',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'"Où habitez-vous ?" demanda-t-elle.',answer:'She asked where I lived.',alternatives:['She asked where we lived.'],hint:'demanda où → asked where',explanation:'Question indirecte avec where.'},
  {id:'rs_2_06',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'He said he was feeling sick that day.',answer:'He said he was feeling sick that day.',hint:'said + he + was',explanation:'Discours indirect : présent → passé.'},
  {id:'rs_2_07',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'She told me she would call later.',answer:'She told me she would call later.',hint:'told + me + she + would',explanation:'"Will" → "would" au discours indirect.'},
  {id:'rs_2_08',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'He asked if I had eaten lunch.',answer:'He asked if I had eaten lunch.',hint:'asked if + past perfect',explanation:'Question indirecte au past perfect.'},
  {id:'rs_2_09',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'They said they could not come to the party.',answer:'They said they could not come to the party.',hint:'said + they + could not',explanation:'"Cannot" → "could not".'},
  {id:'rs_2_10',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'She asked where I was going.',answer:'She asked where I was going.',hint:'asked where + passé',explanation:'Question indirecte : asked where.'},
  {id:'rs_2_11',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['said','she','tired','She','was'],answer:'She said she was tired.',hint:'said + she + was',explanation:'Am → was.'},
  {id:'rs_2_12',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['asked','he','she','where','going','was'],answer:'He asked where she was going.',hint:'asked + where + sujet + was + -ing',explanation:'Question indirecte avec where.'},
  {id:'rs_2_13',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['would','She','she','help','said','me'],answer:'She said she would help me.',hint:'said + she + would',explanation:'"Will" → "would".'},
  {id:'rs_2_14',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['could','He','he','said','swim'],answer:'He said he could swim.',hint:'said + he + could',explanation:'"Can" → "could".'},
  {id:'rs_2_15',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['asked','they','if','coming','were','They'],answer:'They asked if they were coming.',hint:'asked if + sujet + were + -ing',explanation:'Question indirecte : asked if.'},
  // Level 3 (+7)
  {id:'rs_3_01',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'said that',example:'She said that she was very happy to be there.',hint:'"said that" + phrase au passé',explanation:'"Said that" introduit le discours indirect.'},
  {id:'rs_3_02',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'asked if',example:'He asked if I had finished my homework.',hint:'"asked if" + phrase au passé',explanation:'"Asked if" pour les questions oui/non.'},
  {id:'rs_3_03',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'He said he is tired.',answer:'He said he was tired.',hint:'am/is → was (backshifting)',explanation:'Discours indirect : présent → passé.'},
  {id:'rs_3_04',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'She said she will help me.',answer:'She said she would help me.',hint:'will → would',explanation:'"Will" → "would" au discours indirect.'},
  {id:'rs_3_05',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'She said she had never been to France.',answer:"Elle a dit qu'elle n'était jamais allée en France.",hint:'had never been = n\'était jamais allée',explanation:'Past perfect → plus-que-parfait en français.'},
  {id:'rs_3_06',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'He asked me if I liked classical music.',answer:"Il m'a demandé si j'aimais la musique classique.",hint:'asked if = a demandé si',explanation:'Question indirecte en français.'},
  {id:'rs_3_07',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'She said she was studying for her exam and that she would come to the party later.',question:"Que faisait-elle quand il a appelé ?",answer:'She was studying for her exam.',alternatives:['She was studying.'],hint:'Écoutez la première action',explanation:'"Was studying" — discours indirect.'}
);

// ─── FUTURE CONTINUOUS ──────────────────────────────────────────────────────
exercises.futureContinuous.push(
  // Level 1 (+15)
  {id:'fc_1_01',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'This time tomorrow, I ___ flying to Paris.',options:['will be','am','would be','shall'],answer:'will be',hint:'futur continu → will be + -ing',explanation:'"Will be flying" — futur continu.'},
  {id:'fc_1_02',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'She ___ working all day tomorrow.',options:['will be','am being','would be','is'],answer:'will be',hint:'will be + -ing',explanation:'"Will be working."'},
  {id:'fc_1_03',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'___ you be coming to the party?',options:['Will','Would','Shall','Are'],answer:'Will',hint:'question futur continu → Will + sujet + be + -ing',explanation:'"Will you be coming...?"'},
  {id:'fc_1_04',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'At 8pm tonight, we ___ having dinner.',options:['will be','are','would be','shall'],answer:'will be',hint:'action en cours à un moment futur précis',explanation:'"Will be having" — futur continu.'},
  {id:'fc_1_05',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'He ___ sleeping by the time you arrive.',options:['will be','is','would','shall'],answer:'will be',hint:'will be + -ing',explanation:'"Will be sleeping."'},
  {id:'fc_1_06',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'They ___ travelling next week.',options:['will be','are','were','would'],answer:'will be',hint:'action future en cours → will be',explanation:'"Will be travelling."'},
  {id:'fc_1_07',type:'fill-blank',diffLevel:1,instruction:'Complétez avec will be + -ing.',template:'I ___ studying all evening.',answer:'will be studying',hint:'will be + étudier',explanation:'"Will be studying."'},
  {id:'fc_1_08',type:'fill-blank',diffLevel:1,instruction:'Complétez avec will be + -ing.',template:'She ___ waiting for you at the station.',answer:'will be waiting',hint:'will be + attendre',explanation:'"Will be waiting."'},
  {id:'fc_1_09',type:'fill-blank',diffLevel:1,instruction:'Complétez avec will be + -ing.',template:'At this time tomorrow, they ___ flying to London.',answer:'will be flying',hint:'will be + voler',explanation:'"Will be flying."'},
  {id:'fc_1_10',type:'fill-blank',diffLevel:1,instruction:'Complétez avec will be + -ing.',template:'He ___ working late tonight.',answer:'will be working',hint:'will be + travailler',explanation:'"Will be working."'},
  {id:'fc_1_11',type:'fill-blank',diffLevel:1,instruction:'Complétez avec will be + -ing.',template:'We ___ watching the match when you call.',answer:'will be watching',hint:'will be + regarder',explanation:'"Will be watching."'},
  {id:'fc_1_12',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['be','this','will','I','time','studying','tomorrow'],answer:'I will be studying this time tomorrow.',hint:'will + be + -ing',explanation:'"Will be studying this time tomorrow."'},
  {id:'fc_1_13',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['working','be','all','She','will','day'],answer:'She will be working all day.',hint:'will + be + -ing',explanation:'"She will be working all day."'},
  {id:'fc_1_14',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['you','Will','be','coming','tomorrow','?'],answer:'Will you be coming tomorrow?',hint:'Will + sujet + be + -ing?',explanation:'"Will you be coming tomorrow?"'},
  {id:'fc_1_15',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['travelling','be','will','next','They','week'],answer:'They will be travelling next week.',hint:'will + be + -ing',explanation:'"They will be travelling next week."'},
  // Level 2 (+15)
  {id:'fc_2_01',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"Demain à cette heure-ci, je serai en train de voler vers Paris.",answer:'This time tomorrow, I will be flying to Paris.',hint:'futur continu → will be + -ing',explanation:'"Will be flying."'},
  {id:'fc_2_02',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"À 8h ce soir, nous serons en train de dîner.",answer:'At 8pm tonight, we will be having dinner.',hint:'nous serons en train de → we will be + -ing',explanation:'"Will be having dinner."'},
  {id:'fc_2_03',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Est-ce que tu travailleras demain matin ?',answer:'Will you be working tomorrow morning?',hint:'Will + you + be + -ing?',explanation:'"Will you be working?"'},
  {id:'fc_2_04',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Elle dormira quand tu arriveras.',answer:'She will be sleeping when you arrive.',hint:'elle dormira = she will be sleeping',explanation:'"Will be sleeping when you arrive."'},
  {id:'fc_2_05',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Ils seront en train de voyager toute la semaine.',answer:'They will be travelling all week.',hint:'ils seront en train de → will be + -ing',explanation:'"Will be travelling all week."'},
  {id:'fc_2_06',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'I will be studying all evening tomorrow.',answer:'I will be studying all evening tomorrow.',hint:'will be + -ing',explanation:'"Will be studying."'},
  {id:'fc_2_07',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'Will you be joining us for dinner?',answer:'Will you be joining us for dinner?',hint:'Will + sujet + be + -ing?',explanation:'"Will you be joining us?"'},
  {id:'fc_2_08',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'She will be working from home next week.',answer:'She will be working from home next week.',hint:'will be + -ing',explanation:'"Will be working from home."'},
  {id:'fc_2_09',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'They will be celebrating their anniversary this weekend.',answer:'They will be celebrating their anniversary this weekend.',hint:'will be + celebrating',explanation:'"Will be celebrating."'},
  {id:'fc_2_10',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'He will be travelling to New York on Monday.',answer:'He will be travelling to New York on Monday.',hint:'will be + travelling',explanation:'"Will be travelling to New York."'},
  {id:'fc_2_11',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['be','you','Will','tomorrow','working','?'],answer:'Will you be working tomorrow?',hint:'Will + sujet + be + -ing?',explanation:'"Will you be working tomorrow?"'},
  {id:'fc_2_12',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['will','She','the','whole','be','working','day'],answer:'She will be working the whole day.',hint:'will + be + -ing',explanation:'"She will be working the whole day."'},
  {id:'fc_2_13',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['time','be','will','flying','I','this','tomorrow'],answer:'I will be flying this time tomorrow.',hint:'will + be + -ing',explanation:'"I will be flying this time tomorrow."'},
  {id:'fc_2_14',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['be','They','celebrating','tonight','will'],answer:'They will be celebrating tonight.',hint:'will + be + -ing',explanation:'"They will be celebrating tonight."'},
  {id:'fc_2_15',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['sleeping','will','already','He','be','when','arrive','you'],answer:'He will already be sleeping when you arrive.',hint:'will already be + -ing',explanation:'"He will already be sleeping when you arrive."'},
  // Level 3 (+7)
  {id:'fc_3_01',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'will be studying',example:'I will be studying for my exams all weekend.',hint:'"will be studying" = futur continu',explanation:'Action en cours à un moment futur précis.'},
  {id:'fc_3_02',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'will be travelling',example:'She will be travelling around Europe this summer.',hint:'"will be travelling" = en train de voyager',explanation:'Futur continu pour une action planifiée.'},
  {id:'fc_3_03',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'This time tomorrow, I will study English.',answer:'This time tomorrow, I will be studying English.',hint:'action en cours à un moment futur → will be + -ing',explanation:'Futur continu = will be + -ing.'},
  {id:'fc_3_04',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'She will being working all day.',answer:'She will be working all day.',hint:'will + be (pas being)',explanation:'"Will be" + -ing, jamais "will being".'},
  {id:'fc_3_05',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'At this time next year, I will be living in France.',answer:"A cette période l'année prochaine, je vivrai en France.",alternatives:["L'année prochaine à cette époque, je serai en train de vivre en France."],hint:'will be living = je vivrai / serai en train de',explanation:'Futur continu → futur ou présent continu en français.'},
  {id:'fc_3_06',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'Will you be using the computer this afternoon?',answer:"Utiliseras-tu l'ordinateur cet après-midi ?",alternatives:["Est-ce que tu utiliseras l'ordinateur cet après-midi ?"],hint:'Will you be using = utiliseras-tu',explanation:'Question au futur continu.'},
  {id:'fc_3_07',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'This time next week I will be sitting on a beach in Madagascar sipping coconut water.',question:'Que fera la personne à cette heure la semaine prochaine ?',answer:'She will be sitting on a beach in Madagascar.',alternatives:['Sitting on a beach.'],hint:'Écoutez la description de l\'action future',explanation:'"Will be sitting on a beach" — futur continu.'}
);

// ─── FUTURE PERFECT ─────────────────────────────────────────────────────────
exercises.futurePerfect.push(
  // Level 1 (+15)
  {id:'fp_1_01',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'By next year, I ___ finished my studies.',options:['will have','have','would have','shall'],answer:'will have',hint:'avant un moment futur → will have',explanation:'"Will have finished" — futur antérieur.'},
  {id:'fp_1_02',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'By 5pm, she ___ finished the report.',options:['will have','has','would','shall'],answer:'will have',hint:'before a future time → will have',explanation:'"Will have finished by 5pm."'},
  {id:'fp_1_03',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'By the time you arrive, I ___ eaten.',options:['will have','have','would have','shall'],answer:'will have',hint:'avant un futur → will have',explanation:'"Will have eaten by the time you arrive."'},
  {id:'fp_1_04',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'They ___ built the school by 2026.',options:['will have','have','would have','had'],answer:'will have',hint:'by + futur → will have',explanation:'"Will have built by 2026."'},
  {id:'fp_1_05',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'He ___ worked here for 20 years by December.',options:['will have','has','would have','had'],answer:'will have',hint:'by + futur + durée → will have',explanation:'"Will have worked for 20 years."'},
  {id:'fp_1_06',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'___ you finished by tomorrow?',options:['Will you have','Have you','Would you have','Did you'],answer:'Will you have',hint:'question futur antérieur → Will you have?',explanation:'"Will you have finished by tomorrow?"'},
  {id:'fp_1_07',type:'fill-blank',diffLevel:1,instruction:'Complétez avec will have + participe.',template:'By next month, she ___ completed the course.',answer:'will have completed',hint:'will have + participe',explanation:'"Will have completed."'},
  {id:'fp_1_08',type:'fill-blank',diffLevel:1,instruction:'Complétez avec will have + participe.',template:'By the time we arrive, he ___ already eaten.',answer:'will have already eaten',alternatives:['will have eaten'],hint:'will have + already + participe',explanation:'"Will have already eaten."'},
  {id:'fp_1_09',type:'fill-blank',diffLevel:1,instruction:'Complétez avec will have + participe.',template:'They ___ finished the project by Friday.',answer:'will have finished',hint:'will have + participe',explanation:'"Will have finished by Friday."'},
  {id:'fp_1_10',type:'fill-blank',diffLevel:1,instruction:'Complétez avec will have + participe.',template:'I ___ read the book by tonight.',answer:'will have read',hint:'will have + participe',explanation:'"Will have read by tonight."'},
  {id:'fp_1_11',type:'fill-blank',diffLevel:1,instruction:'Complétez avec will have + participe.',template:'By 2030, scientists ___ found new cures.',answer:'will have found',hint:'will have + participe',explanation:'"Will have found."'},
  {id:'fp_1_12',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['will','have','I','by','finished','tonight'],answer:'I will have finished by tonight.',hint:'will + have + participe',explanation:'"I will have finished by tonight."'},
  {id:'fp_1_13',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['have','built','will','By','they','2030','the','bridge'],answer:'By 2030, they will have built the bridge.',hint:'By + date, will + have + participe',explanation:'"By 2030, they will have built."'},
  {id:'fp_1_14',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['you','Will','have','finished','by','noon','?'],answer:'Will you have finished by noon?',hint:'Will + sujet + have + participe?',explanation:'"Will you have finished by noon?"'},
  {id:'fp_1_15',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['already','will','She','have','left','time','arrive','you','by','the'],answer:'She will have already left by the time you arrive.',hint:'will + have + already + participe',explanation:'"Will have already left by the time you arrive."'},
  // Level 2 (+15)
  {id:'fp_2_01',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"D'ici la fin du mois, j'aurai fini le projet.",answer:'By the end of the month, I will have finished the project.',hint:'j\'aurai fini → I will have finished',explanation:'"Will have finished" — futur antérieur.'},
  {id:'fp_2_02',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Quand tu arriveras, nous aurons déjà mangé.',answer:'By the time you arrive, we will have already eaten.',alternatives:['When you arrive, we will have already eaten.'],hint:'nous aurons mangé → we will have eaten',explanation:'"Will have already eaten."'},
  {id:'fp_2_03',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"D'ici 2030, les scientifiques auront trouvé de nouveaux remèdes.",answer:'By 2030, scientists will have found new cures.',hint:'auront trouvé → will have found',explanation:'"Will have found by 2030."'},
  {id:'fp_2_04',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Aura-t-elle fini avant demain ?',answer:'Will she have finished by tomorrow?',hint:'aura-t-elle fini → will she have finished',explanation:'Question futur antérieur.'},
  {id:'fp_2_05',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"Il travaillera ici depuis 10 ans en décembre.",answer:'By December, he will have worked here for ten years.',hint:'il aura travaillé → will have worked',explanation:'"Will have worked for ten years."'},
  {id:'fp_2_06',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'By the time you wake up I will have left.',answer:'By the time you wake up I will have left.',hint:'will + have + participe',explanation:'"Will have left."'},
  {id:'fp_2_07',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'She will have finished her studies by next year.',answer:'She will have finished her studies by next year.',hint:'will have + participe',explanation:'"Will have finished."'},
  {id:'fp_2_08',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'Will you have completed the report by Friday?',answer:'Will you have completed the report by Friday?',hint:'Will + sujet + have + participe?',explanation:'Question futur antérieur.'},
  {id:'fp_2_09',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'They will have been married for twenty-five years by June.',answer:'They will have been married for twenty-five years by June.',hint:'will have been + participe',explanation:'"Will have been married for 25 years."'},
  {id:'fp_2_10',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'By 2025 we will have solved the problem.',answer:'By 2025 we will have solved the problem.',hint:'will have + participe',explanation:'"Will have solved."'},
  {id:'fp_2_11',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['have','you','by','finished','Will','tomorrow','?'],answer:'Will you have finished by tomorrow?',hint:'Will + sujet + have + participe?',explanation:'"Will you have finished by tomorrow?"'},
  {id:'fp_2_12',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['will','She','have','passed','her','by','exam','June'],answer:'She will have passed her exam by June.',hint:'will + have + participe',explanation:'"Will have passed by June."'},
  {id:'fp_2_13',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['already','By','you','the','will','have','left','time','I'],answer:'By the time I arrive, you will have already left.',hint:'By the time, will have already + participe',explanation:'"Will have already left."'},
  {id:'fp_2_14',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['built','They','have','will','the','2030','by','hospital'],answer:'They will have built the hospital by 2030.',hint:'will + have + participe',explanation:'"Will have built by 2030."'},
  {id:'fp_2_15',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['have','By','studied','I','next','will','French','year','for','five','years'],answer:'By next year, I will have studied French for five years.',hint:'will have + participe + for',explanation:'"Will have studied for five years."'},
  // Level 3 (+7)
  {id:'fp_3_01',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'will have finished',example:'By this time tomorrow, I will have finished the exam.',hint:'"will have finished" + délai futur',explanation:'Futur antérieur : action accomplie avant un moment futur.'},
  {id:'fp_3_02',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'will have lived',example:'By 2030, she will have lived in France for ten years.',hint:'"will have lived" + for + durée',explanation:'"Will have lived" — durée accomplie à un moment futur.'},
  {id:'fp_3_03',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'By tomorrow, I will finished the report.',answer:'By tomorrow, I will have finished the report.',hint:'futur antérieur = will have + participe',explanation:'"Will have finished" — futur antérieur.'},
  {id:'fp_3_04',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'She will have went to Paris by June.',answer:'She will have gone to Paris by June.',hint:'participe de go = gone',explanation:'"Gone" = participe passé de "go".'},
  {id:'fp_3_05',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'By the time you arrive, we will have eaten.',answer:'Quand tu arriveras, nous aurons déjà mangé.',hint:'will have eaten = aurons mangé',explanation:'Futur antérieur en français.'},
  {id:'fp_3_06',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'Will they have finished the project by December?',answer:"Auront-ils terminé le projet d'ici décembre ?",hint:'will they have finished? = auront-ils terminé?',explanation:'Futur antérieur interrogatif.'},
  {id:'fp_3_07',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'By the end of this year I will have lived in Madagascar for five years.',question:"Depuis combien de temps la personne vit-elle à Madagascar en fin d'année ?",answer:'For five years.',alternatives:['Five years.'],hint:'Écoutez "for five years"',explanation:'"Will have lived for five years" — durée accomplie.'}
);
"""

with open(EXERCISES_PATH, encoding='utf-8') as f:
    src = f.read()

insert_pos = src.index('export function getAllExercises()')
new_src = src[:insert_pos] + NEW + '\n' + src[insert_pos:]

with open(EXERCISES_PATH, 'w', encoding='utf-8') as f:
    f.write(new_src)

print('Batch 2 done: pastContinuous, presentPerfect, pastPerfect, timeMarkers, conditionals, passiveVoice, reportedSpeech, futureContinuous, futurePerfect')
