#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Appends all new level-structured exercises to exercises.js"""

import sys, os
sys.stdout.reconfigure(encoding='utf-8')

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXERCISES_PATH = os.path.join(BASE, 'src', 'data', 'exercises.js')

# ---------------------------------------------------------------------------
# NEW EXERCISES — 15 per diffLevel per grammar topic
# L1: 6 MC + 5 fill-blank + 4 word-order
# L2: 5 translate + 5 listening + 5 word-order
# L3: 4 free-production + 4 error-correct + 4 translate-fr + 3 listening-comp
# ---------------------------------------------------------------------------

NEW = r"""
// ─── NEW LEVEL EXERCISES (diffLevel 1 / 2 / 3) ──────────────────────────────

// ─── ARTICLES ───────────────────────────────────────────────────────────────
exercises.articles.push(
  // Level 1 (+10)
  {id:'art_1_01',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'___ elephant never forgets.',options:['a','an','the','—'],answer:'an',hint:'elephant → voyelle',explanation:'"An" devant les sons vocaliques.'},
  {id:'art_1_02',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'She is ___ doctor.',options:['a','an','the','—'],answer:'a',hint:'doctor → consonne',explanation:'"A" devant les consonnes.'},
  {id:'art_1_03',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'___ moon is beautiful tonight.',options:['a','an','the','—'],answer:'The',hint:'unique → the',explanation:'"The" pour les objets uniques.'},
  {id:'art_1_04',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'I drink ___ water every day.',options:['a','an','the','—'],answer:'—',hint:'water non-dénombrable au général',explanation:'Pas d\'article avec les non-dénombrables au sens général.'},
  {id:'art_1_05',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'He plays ___ guitar.',options:['a','an','the','—'],answer:'the',hint:'instruments → the',explanation:'"Play the guitar/piano" toujours avec "the".'},
  {id:'art_1_06',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'She is ___ honest woman.',options:['a','an','the','—'],answer:'an',hint:'honest : h muet → son /ɒ/',explanation:'"An honest" car le h est muet.'},
  {id:'art_1_07',type:'fill-blank',diffLevel:1,instruction:'Complétez avec a, an ou the.',template:'I saw ___ old man near the market.',answer:'an',hint:'old → son vocalique',explanation:'"An old" — "old" commence par /əʊ/.'},
  {id:'art_1_08',type:'fill-blank',diffLevel:1,instruction:'Complétez avec a, an ou the.',template:'Close ___ door, it is cold.',answer:'the',hint:'porte spécifique → the',explanation:'"The door" = porte spécifique connue des deux.'},
  {id:'art_1_09',type:'fill-blank',diffLevel:1,instruction:'Complétez avec a, an ou the.',template:'___ Nile is the longest river in Africa.',answer:'The',hint:'fleuves → the',explanation:'"The Nile" — on met "the" devant les noms de fleuves.'},
  {id:'art_1_10',type:'fill-blank',diffLevel:1,instruction:'Complétez avec a, an ou the.',template:'She reads ___ book every night.',answer:'a',hint:'première mention → a',explanation:'"A book" = première mention générale.'},
  {id:'art_1_11',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['an','is','He','engineer'],answer:'He is an engineer.',hint:'an + engineer (voyelle)',explanation:'"An engineer" — voyelle /ɛ/.'},
  {id:'art_1_12',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['a','She','bought','new','dress'],answer:'She bought a new dress.',hint:'a + dress',explanation:'"A new dress" — première mention.'},
  {id:'art_1_13',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['the','in','school','is','library','The'],answer:'The library is in the school.',hint:'library et school = spécifiques',explanation:'"The library" et "the school" = institutions spécifiques.'},
  {id:'art_1_14',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['at','They','the','play','beach'],answer:'They play at the beach.',hint:'the beach = lieu spécifique',explanation:'"The beach" = lieu identifié.'},
  // Level 2 (+14)
  {id:'art_2_01',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"C'est une idée intéressante.",answer:'It is an interesting idea.',alternatives:["It's an interesting idea."],hint:'interesting → voyelle → an',explanation:'"An interesting idea".'},
  {id:'art_2_02',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Le soleil se lève à six heures.',answer:'The sun rises at six.',alternatives:['The sun rises at 6 am.'],hint:'Le soleil → The sun',explanation:'"The sun" — objet unique.'},
  {id:'art_2_03',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"J'achète du riz au marché.",answer:'I buy rice at the market.',hint:'du riz → rice (sans article)',explanation:'"Rice" au sens général = sans article.'},
  {id:'art_2_04',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Il joue du piano chaque soir.',answer:'He plays the piano every evening.',hint:'instruments → the',explanation:'"Play the piano".'},
  {id:'art_2_05',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"Elle est infirmière à l'hôpital.",answer:'She is a nurse at the hospital.',hint:'nurse → a ; hospital → the',explanation:'"A nurse" (métier, consonne). "The hospital" (institution).'},
  {id:'art_2_06',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'She has a cat and an umbrella.',answer:'She has a cat and an umbrella.',hint:'cat → a ; umbrella → an',explanation:'"A cat" et "an umbrella".'},
  {id:'art_2_07',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'The children are playing in the garden.',answer:'The children are playing in the garden.',hint:'the children, the garden',explanation:'Références spécifiques.'},
  {id:'art_2_08',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'I need a pen and an eraser.',answer:'I need a pen and an eraser.',hint:'pen → a ; eraser → an',explanation:'"A pen" et "an eraser".'},
  {id:'art_2_09',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'He is the best student in the class.',answer:'He is the best student in the class.',hint:'superlatif → the',explanation:'"The best" = superlatif.'},
  {id:'art_2_10',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'I live near an old church.',answer:'I live near an old church.',hint:'old → son vocalique → an',explanation:'"An old church".'},
  {id:'art_2_11',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['the','is','She','in','kitchen'],answer:'She is in the kitchen.',hint:'the kitchen',explanation:'"The kitchen" = pièce spécifique.'},
  {id:'art_2_12',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['a','is','There','market','near','here'],answer:'There is a market near here.',hint:'a market = première mention',explanation:'"A market" = non spécifié.'},
  {id:'art_2_13',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['the','best','is','He','student','class','in','the'],answer:'He is the best student in the class.',hint:'superlatif → the',explanation:'"The best student".'},
  {id:'art_2_14',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['an','went','She','to','interview'],answer:'She went to an interview.',hint:'interview → an',explanation:'"An interview" — voyelle /ɪ/.'},
  {id:'art_2_15',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['the','to','go','They','school','every','day'],answer:'They go to school every day.',hint:'school = institution',explanation:'"Go to school" sans article = expression idiomatique.'},
  // Level 3 (+13)
  {id:'art_3_01',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'an',example:'I have an orange in my bag.',hint:'"an" devant son vocalique',explanation:'"An" + voyelle : an apple, an egg, an hour.'},
  {id:'art_3_02',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'the',example:'The sun is very hot today.',hint:'"the" pour quelque chose de spécifique',explanation:'"The" = article défini.'},
  {id:'art_3_03',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'a',example:'I saw a dog in the street.',hint:'"a" devant consonne',explanation:'"A" = article indéfini, consonne.'},
  {id:'art_3_04',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'the best',example:'She is the best teacher in the school.',hint:'superlatif → the',explanation:'"The best/most/tallest" — superlatifs.'},
  {id:'art_3_05',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'He is a honest man.',answer:'He is an honest man.',hint:'Honest : h muet',explanation:'"An honest" — le h est muet.'},
  {id:'art_3_06',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'She plays a piano very well.',answer:'She plays the piano very well.',hint:'instruments → the',explanation:'"Play the piano".'},
  {id:'art_3_07',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'I drink the milk every morning.',answer:'I drink milk every morning.',hint:'milk au sens général',explanation:'Non-dénombrable au sens général = sans article.'},
  {id:'art_3_08',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'She is best student in the class.',answer:'She is the best student in the class.',hint:'superlatif → the best',explanation:'"The best" = superlatif.'},
  {id:'art_3_09',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'She is an excellent doctor.',answer:'Elle est une excellente médecin.',alternatives:['Elle est un excellent médecin.'],hint:'an excellent → une excellente',explanation:'"An excellent" → "une excellente".'},
  {id:'art_3_10',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'The children love the beach.',answer:'Les enfants adorent la plage.',hint:'The = les/la',explanation:'"The children" = "les enfants".'},
  {id:'art_3_11',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'I need a doctor urgently.',answer:"J'ai besoin d'un médecin d'urgence.",hint:'a doctor = un médecin',explanation:'"A doctor" = "un médecin".'},
  {id:'art_3_12',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'He plays the guitar and sings.',answer:'Il joue de la guitare et chante.',hint:'play the guitar = jouer de la guitare',explanation:'"Play the guitar" = "jouer de la guitare".'},
  {id:'art_3_13',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'I saw a dog and an elephant at the zoo.',question:'Quel article est utilisé avec elephant ?',answer:'an',alternatives:['An'],hint:'elephant → voyelle',explanation:'"An elephant" — voyelle /ɛ/.'},
  {id:'art_3_14',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'The sun is shining and the sky is blue.',question:'Pourquoi utilise-t-on "the" avec sun et sky ?',answer:'They are unique objects.',alternatives:['They are unique.','Sun and sky are unique.'],hint:'Objets uniques → the',explanation:'"The sun" et "the sky" sont uniques.'},
  {id:'art_3_15',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'She is a teacher and her husband is an engineer.',question:'Quel est le métier du mari ?',answer:'He is an engineer.',alternatives:['an engineer','engineer'],hint:'Écoutez le deuxième métier',explanation:'"An engineer" — voyelle /ɛ/.'}
);

// ─── PLURALS ─────────────────────────────────────────────────────────────────
exercises.plurals.push(
  // Level 1 (+10)
  {id:'pl_1_01',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon pluriel.',question:'One child → two ___',options:['childs','children','childrens','child'],answer:'children',hint:'Irrégulier',explanation:'"Children" est le pluriel irrégulier de "child".'},
  {id:'pl_1_02',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon pluriel.',question:'One city → many ___',options:['citys','cities','cityes','city'],answer:'cities',hint:'consonne + y → ies',explanation:'"City" → retire y, ajoute -ies → "cities".'},
  {id:'pl_1_03',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon pluriel.',question:'One knife → two ___',options:['knifes','knives','knifes','knife'],answer:'knives',hint:'f/fe → ves',explanation:'"Knife" → "knives" (f → ves).'},
  {id:'pl_1_04',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon pluriel.',question:'One tooth → many ___',options:['tooths','teeths','teeth','tooth'],answer:'teeth',hint:'Irrégulier',explanation:'"Tooth" → "teeth" (irrégulier).'},
  {id:'pl_1_05',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon pluriel.',question:'One sheep → two ___',options:['sheeps','sheepes','sheep','sheeps'],answer:'sheep',hint:'Invariable',explanation:'"Sheep" → "sheep" (invariable).'},
  {id:'pl_1_06',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon pluriel.',question:'One box → three ___',options:['boxs','boxes','boxies','box'],answer:'boxes',hint:'-s, -x, -ch, -sh → +es',explanation:'"Box" → "boxes" (finit en -x → +es).'},
  {id:'pl_1_07',type:'fill-blank',diffLevel:1,instruction:'Donnez le pluriel.',template:'One man → two ___',answer:'men',hint:'Irrégulier',explanation:'"Man" → "men" (irrégulier).'},
  {id:'pl_1_08',type:'fill-blank',diffLevel:1,instruction:'Donnez le pluriel.',template:'One woman → three ___',answer:'women',hint:'Irrégulier',explanation:'"Woman" → "women" (irrégulier).'},
  {id:'pl_1_09',type:'fill-blank',diffLevel:1,instruction:'Donnez le pluriel.',template:'One leaf → five ___',answer:'leaves',hint:'f → ves',explanation:'"Leaf" → "leaves" (f → ves).'},
  {id:'pl_1_10',type:'fill-blank',diffLevel:1,instruction:'Donnez le pluriel.',template:'One tomato → many ___',answer:'tomatoes',hint:'-o → +es',explanation:'"Tomato" → "tomatoes" (-o → +es).'},
  {id:'pl_1_11',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['The','are','children','happy'],answer:'The children are happy.',hint:'children = pluriel de child',explanation:'"The children are" — "children" est pluriel → "are".'},
  {id:'pl_1_12',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['have','I','three','brothers'],answer:'I have three brothers.',hint:'brother → brothers',explanation:'"Brothers" = pluriel régulier de "brother".'},
  {id:'pl_1_13',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['are','in','the','Mice','house'],answer:'Mice are in the house.',hint:'mouse → mice',explanation:'"Mouse" → "mice" (irrégulier).'},
  {id:'pl_1_14',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['two','She','has','knives'],answer:'She has two knives.',hint:'knife → knives',explanation:'"Knife" → "knives" (f → ves).'},
  // Level 2 (+14)
  {id:'pl_2_01',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Il y a beaucoup de gens dans la rue.',answer:'There are many people in the street.',alternatives:['There are a lot of people in the street.'],hint:'people = pluriel de person',explanation:'"People" est déjà pluriel.'},
  {id:'pl_2_02',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Les femmes travaillent à l\'hôpital.',answer:'The women work at the hospital.',hint:'woman → women',explanation:'"Women" = pluriel de "woman".'},
  {id:'pl_2_03',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'J\'ai trois dents abîmées.',answer:'I have three damaged teeth.',alternatives:['I have three broken teeth.'],hint:'dent → tooth → teeth',explanation:'"Tooth" → "teeth" (irrégulier).'},
  {id:'pl_2_04',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Les souris mangent le fromage.',answer:'The mice eat the cheese.',hint:'mouse → mice',explanation:'"Mouse" → "mice" (irrégulier).'},
  {id:'pl_2_05',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Il y a cinq poissons dans le bassin.',answer:'There are five fish in the pond.',alternatives:['There are five fishes in the pond.'],hint:'fish peut rester invariable',explanation:'"Fish" reste souvent invariable, mais "fishes" est aussi accepté.'},
  {id:'pl_2_06',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'The children are playing outside.',answer:'The children are playing outside.',hint:'children = pluriel',explanation:'"Children" = pluriel de "child".'},
  {id:'pl_2_07',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'I see two geese on the lake.',answer:'I see two geese on the lake.',hint:'goose → geese',explanation:'"Goose" → "geese" (irrégulier).'},
  {id:'pl_2_08',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'Her teeth are very white.',answer:'Her teeth are very white.',hint:'tooth → teeth',explanation:'"Teeth" = pluriel de "tooth".'},
  {id:'pl_2_09',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'The men are waiting outside.',answer:'The men are waiting outside.',hint:'man → men',explanation:'"Men" = pluriel de "man".'},
  {id:'pl_2_10',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'She has five sheep on her farm.',answer:'She has five sheep on her farm.',hint:'sheep = invariable',explanation:'"Sheep" = invariable.'},
  {id:'pl_2_11',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['are','The','in','oxen','the','field'],answer:'The oxen are in the field.',hint:'ox → oxen',explanation:'"Ox" → "oxen" (irrégulier ancien).'},
  {id:'pl_2_12',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['have','many','We','responsibilities'],answer:'We have many responsibilities.',hint:'responsibility → responsibilities',explanation:'"Responsibility" → "responsibilities" (-y → -ies).'},
  {id:'pl_2_13',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['The','beautiful','are','butterflies'],answer:'The butterflies are beautiful.',hint:'butterfly → butterflies',explanation:'"Butterfly" → "butterflies" (-y → -ies).'},
  {id:'pl_2_14',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['gave','three','She','sandwiches','me'],answer:'She gave me three sandwiches.',hint:'sandwich → sandwiches',explanation:'"Sandwich" → "sandwiches" (-ch → +es).'},
  {id:'pl_2_15',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['lives','in','A','the','deer','forest'],answer:'A deer lives in the forest.',hint:'deer = invariable',explanation:'"Deer" = invariable.'},
  // Level 3 (+13)
  {id:'pl_3_01',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'children',example:'The children are playing in the garden.',hint:'Pluriel irrégulier de child',explanation:'"Children" = pluriel de "child".'},
  {id:'pl_3_02',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'teeth',example:'I brush my teeth every morning.',hint:'Pluriel de tooth',explanation:'"Teeth" = pluriel de "tooth".'},
  {id:'pl_3_03',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'women',example:'The women are very kind.',hint:'Pluriel de woman',explanation:'"Women" = pluriel de "woman".'},
  {id:'pl_3_04',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'leaves',example:'The leaves are falling from the trees.',hint:'leaf → leaves',explanation:'"Leaf" → "leaves" (f → ves).'},
  {id:'pl_3_05',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'He has two childs at school.',answer:'He has two children at school.',hint:'Pluriel irrégulier de child',explanation:'"Child" → "children".'},
  {id:'pl_3_06',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'I see three sheeps in the field.',answer:'I see three sheep in the field.',hint:'sheep = invariable',explanation:'"Sheep" ne change pas au pluriel.'},
  {id:'pl_3_07',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'She has beautiful tooths.',answer:'She has beautiful teeth.',hint:'Pluriel irrégulier de tooth',explanation:'"Tooth" → "teeth".'},
  {id:'pl_3_08',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'There are five womans in the room.',answer:'There are five women in the room.',hint:'Pluriel irrégulier de woman',explanation:'"Woman" → "women".'},
  {id:'pl_3_09',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'The mice ran away quickly.',answer:'Les souris se sont enfuies rapidement.',alternatives:['Les souris ont vite disparu.'],hint:'mice = les souris',explanation:'"Mice" = pluriel de "mouse" = "souris".'},
  {id:'pl_3_10',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'The children played all day.',answer:'Les enfants ont joué toute la journée.',hint:'children = les enfants',explanation:'"Children" = "les enfants".'},
  {id:'pl_3_11',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'She has two cats and three dogs.',answer:'Elle a deux chats et trois chiens.',hint:'cats = chats, dogs = chiens',explanation:'Pluriels réguliers : cats, dogs.'},
  {id:'pl_3_12',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'The leaves are orange and red in autumn.',answer:'Les feuilles sont orange et rouges en automne.',hint:'leaves = les feuilles',explanation:'"Leaves" = pluriel de "leaf" = "feuilles".'},
  {id:'pl_3_13',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'There are three children and two women in the park.',question:'Combien de personnes y a-t-il en tout ?',answer:'Five.',alternatives:['5.','Five people.'],hint:'3 + 2 = ?',explanation:'Three children + two women = five people.'},
  {id:'pl_3_14',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'I see two geese and one deer near the river.',question:'Quel animal apparaît une seule fois ?',answer:'A deer.',alternatives:['deer','The deer'],hint:'Écoutez les quantités',explanation:'"One deer" = singulier.'},
  {id:'pl_3_15',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'The men and women work together in the office.',question:'Quel est le pluriel de man utilisé ici ?',answer:'men',alternatives:['Men'],hint:'man → ?',explanation:'"Men" = pluriel irrégulier de "man".'}
);

// ─── THERE IS / ARE ──────────────────────────────────────────────────────────
exercises.therebeis.push(
  // Level 1 (+11)
  {id:'tbi_1_01',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'___ a book on the table.',options:['There is','There are','There has','There have'],answer:'There is',hint:'a book = singulier',explanation:'"There is" + singulier.'},
  {id:'tbi_1_02',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'___ three students in the classroom.',options:['There is','There are','There was','There have'],answer:'There are',hint:'three students = pluriel',explanation:'"There are" + pluriel.'},
  {id:'tbi_1_03',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'___ any milk in the fridge?',options:['Is there','Are there','Has there','Have there'],answer:'Is there',hint:'milk = non-dénombrable → is',explanation:'"Is there any milk?" — milk est non-dénombrable.'},
  {id:'tbi_1_04',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'___ many people at the party last night.',options:['There were','There was','There are','There is'],answer:'There were',hint:'last night = passé + pluriel',explanation:'"There were" = pluriel passé.'},
  {id:'tbi_1_05',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'___ no sugar left.',options:["There isn't","There aren't",'There was not','There not'],answer:"There isn't",hint:'sugar = non-dénombrable → is',explanation:'"There isn\'t any sugar" — non-dénombrable.'},
  {id:'tbi_1_06',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'___ an elephant in the zoo.',options:['There is','There are','There be','There has'],answer:'There is',hint:'an elephant = singulier',explanation:'"There is an elephant" — singulier.'},
  {id:'tbi_1_07',type:'fill-blank',diffLevel:1,instruction:'Complétez avec there is/are.',template:'___ a hospital near the school.',answer:'There is',hint:'hospital = singulier',explanation:'"There is a hospital" — singulier.'},
  {id:'tbi_1_08',type:'fill-blank',diffLevel:1,instruction:'Complétez avec there is/are.',template:'___ many birds in the trees.',answer:'There are',hint:'many birds = pluriel',explanation:'"There are many birds" — pluriel.'},
  {id:'tbi_1_09',type:'fill-blank',diffLevel:1,instruction:'Complétez avec there is/are.',template:'___ no water in the glass.',answer:"There isn't",alternatives:['There is no'],hint:'water = non-dénombrable → is',explanation:'"There isn\'t any water" ou "There is no water".'},
  {id:'tbi_1_10',type:'fill-blank',diffLevel:1,instruction:'Complétez avec there is/are.',template:'___ a fly in my soup!',answer:'There is',hint:'a fly = singulier',explanation:'"There is a fly" — singulier.'},
  {id:'tbi_1_11',type:'fill-blank',diffLevel:1,instruction:'Complétez avec there is/are.',template:'___ five chairs around the table.',answer:'There are',hint:'five chairs = pluriel',explanation:'"There are five chairs" — pluriel.'},
  {id:'tbi_1_12',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['a','is','There','pharmacy','here','near'],answer:'There is a pharmacy near here.',hint:'There is + singulier',explanation:'"There is a pharmacy" — singulier.'},
  {id:'tbi_1_13',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['Are','questions','there','any','?'],answer:'Are there any questions?',hint:'Question : Are there...?',explanation:'Question : "Are there any questions?"'},
  {id:'tbi_1_14',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['were','at','There','people','market','many','the'],answer:'There were many people at the market.',hint:'passé pluriel → were',explanation:'"There were" = passé pluriel.'},
  // Level 2 (+12)
  {id:'tbi_2_01',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"Il y a un chien dans le jardin.",answer:'There is a dog in the garden.',alternatives:["There's a dog in the garden."],hint:'un chien = a dog (singulier)',explanation:'"There is a dog" — singulier.'},
  {id:'tbi_2_02',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Il y a beaucoup de gens dans la rue.',answer:'There are many people in the street.',alternatives:['There are a lot of people in the street.'],hint:'beaucoup de gens = many people (pluriel)',explanation:'"There are many people" — pluriel.'},
  {id:'tbi_2_03',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"Y a-t-il une école ici ?",answer:'Is there a school here?',hint:'Question singulier : Is there...?',explanation:'"Is there a school?" — question singulier.'},
  {id:'tbi_2_04',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"Il n'y a pas de lait dans le frigo.",answer:"There isn't any milk in the fridge.",alternatives:['There is no milk in the fridge.'],hint:'pas de lait → no milk / not any milk',explanation:'"There isn\'t any milk" ou "There is no milk".'},
  {id:'tbi_2_05',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:"Il y avait cinq voitures dans la rue.",answer:'There were five cars in the street.',hint:'passé pluriel → were',explanation:'"There were five cars" — passé pluriel.'},
  {id:'tbi_2_06',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'There is a cat on the roof.',answer:'There is a cat on the roof.',hint:'a cat = singulier → is',explanation:'"There is a cat".'},
  {id:'tbi_2_07',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'There are three books on the table.',answer:'There are three books on the table.',hint:'three books = pluriel → are',explanation:'"There are three books".'},
  {id:'tbi_2_08',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'Is there a market near here?',answer:'Is there a market near here?',hint:'Question → Is there...?',explanation:'Question singulier.'},
  {id:'tbi_2_09',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'There were many animals in the forest.',answer:'There were many animals in the forest.',hint:'passé pluriel → were',explanation:'"There were many animals".'},
  {id:'tbi_2_10',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:"There isn't any sugar in the kitchen.",answer:"There isn't any sugar in the kitchen.",hint:'sugar non-dénombrable → is',explanation:'"There isn\'t any sugar".'},
  {id:'tbi_2_11',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['many','Are','shops','there','here','near','?'],answer:'Are there many shops near here?',hint:'Question pluriel',explanation:'"Are there many shops?" — pluriel.'},
  {id:'tbi_2_12',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['a','was','There','problem','yesterday'],answer:'There was a problem yesterday.',hint:'passé singulier → was',explanation:'"There was a problem" — passé singulier.'},
  {id:'tbi_2_13',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['any','there','Are','questions','?'],answer:'Are there any questions?',hint:'Questions → Are there...?',explanation:'"Are there any questions?"'},
  {id:'tbi_2_14',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['no','There','the','is','bus','today'],answer:'There is no bus today.',hint:'There is no = il n\'y a pas de',explanation:'"There is no bus" = "There isn\'t a bus".'},
  {id:'tbi_2_15',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['a','There','in','is','garden','bee','the'],answer:'There is a bee in the garden.',hint:'a bee = singulier',explanation:'"There is a bee" — singulier.'},
  // Level 3 (+14)
  {id:'tbi_3_01',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'there is',example:'There is a beautiful lake near our village.',hint:'"There is" + singulier',explanation:'"There is" exprime l\'existence d\'un objet singulier.'},
  {id:'tbi_3_02',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'there are',example:'There are many students in the classroom.',hint:'"There are" + pluriel',explanation:'"There are" exprime l\'existence de plusieurs objets.'},
  {id:'tbi_3_03',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'there were',example:'There were many people at the festival.',hint:'"There were" = passé pluriel',explanation:'"There were" = passé de "there are".'},
  {id:'tbi_3_04',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:"there isn't",example:"There isn't any milk in the fridge.",hint:'"There isn\'t" = négatif singulier',explanation:'"There isn\'t" = "there is not".'},
  {id:'tbi_3_05',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'There are a dog in the garden.',answer:'There is a dog in the garden.',hint:'a dog = singulier → is',explanation:'"A dog" = singulier → "there is".'},
  {id:'tbi_3_06',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'Is there many people here?',answer:'Are there many people here?',hint:'many people = pluriel → are',explanation:'"Many people" = pluriel → "Are there...?"'},
  {id:'tbi_3_07',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'There were a problem yesterday.',answer:'There was a problem yesterday.',hint:'a problem = singulier → was',explanation:'"A problem" = singulier → "there was".'},
  {id:'tbi_3_08',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:"There isn't any books left.",answer:"There aren't any books left.",hint:'books = pluriel → aren\'t',explanation:'"Books" = pluriel → "there aren\'t".'},
  {id:'tbi_3_09',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'There is a market every Sunday.',answer:'Il y a un marché tous les dimanches.',hint:'There is = il y a',explanation:'"There is" = "il y a" (singulier).'},
  {id:'tbi_3_10',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'There are many birds in Madagascar.',answer:'Il y a beaucoup d\'oiseaux à Madagascar.',hint:'There are = il y a',explanation:'"There are" = "il y a" (pluriel).'},
  {id:'tbi_3_11',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:"There isn't any water in the glass.",answer:"Il n'y a pas d'eau dans le verre.",hint:"There isn't = il n'y a pas",explanation:'"There isn\'t" = "il n\'y a pas".'},
  {id:'tbi_3_12',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'Were there many students at the ceremony?',answer:'Y avait-il beaucoup d\'étudiants à la cérémonie ?',hint:'Were there...? = Y avait-il ?',explanation:'"Were there...?" = "Y avait-il...?" (passé).'},
  {id:'tbi_3_13',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'There are two cats and one dog in the house.',question:'Combien d\'animaux y a-t-il en tout ?',answer:'Three.',alternatives:['3.','Three animals.'],hint:'2 + 1 = ?',explanation:'Two cats + one dog = three animals.'},
  {id:'tbi_3_14',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'There is no school today because of the rain.',question:'Y a-t-il école aujourd\'hui ?',answer:'No, there is no school today.',alternatives:['No.','No school today.'],hint:'Écoutez la négation',explanation:'"There is no school" = pas d\'école.'},
  {id:'tbi_3_15',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'There were five people at the meeting yesterday.',question:'Quand a eu lieu la réunion ?',answer:'Yesterday.',alternatives:['Last night.','Yesterday morning.'],hint:'Écoutez l\'adverbe de temps',explanation:'"Yesterday" = hier.'}
);

// ─── PREPOSITIONS ─────────────────────────────────────────────────────────────
exercises.prepositions.push(
  // Level 1 (+11)
  {id:'prep_1_01',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne préposition.',question:'I wake up ___ 6 o\'clock.',options:['in','on','at','by'],answer:'at',hint:'heure précise → at',explanation:'"At" pour les heures précises.'},
  {id:'prep_1_02',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne préposition.',question:'School starts ___ Monday.',options:['in','on','at','by'],answer:'on',hint:'jours → on',explanation:'"On" pour les jours de la semaine.'},
  {id:'prep_1_03',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne préposition.',question:'My birthday is ___ June.',options:['in','on','at','by'],answer:'in',hint:'mois → in',explanation:'"In" pour les mois et les années.'},
  {id:'prep_1_04',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne préposition.',question:'The keys are ___ the table.',options:['in','on','at','under'],answer:'on',hint:'sur la surface → on',explanation:'"On" pour une surface.'},
  {id:'prep_1_05',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne préposition.',question:'We go to church ___ Sunday mornings.',options:['in','on','at','by'],answer:'on',hint:'jour + moment → on',explanation:'"On Sunday mornings" = les matins du dimanche.'},
  {id:'prep_1_06',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne préposition.',question:'She was born ___ 1998.',options:['in','on','at','by'],answer:'in',hint:'année → in',explanation:'"In 1998" — années avec "in".'},
  {id:'prep_1_07',type:'fill-blank',diffLevel:1,instruction:'Complétez avec in, on ou at.',template:'The cat is ___ the box.',answer:'in',hint:'à l\'intérieur → in',explanation:'"In" = à l\'intérieur.'},
  {id:'prep_1_08',type:'fill-blank',diffLevel:1,instruction:'Complétez avec in, on ou at.',template:'We meet ___ noon.',answer:'at',hint:'noon = moment précis → at',explanation:'"At noon" — moment précis.'},
  {id:'prep_1_09',type:'fill-blank',diffLevel:1,instruction:'Complétez avec in, on ou at.',template:'She was born ___ a Sunday.',answer:'on',hint:'jour → on',explanation:'"On a Sunday" — jour.'},
  {id:'prep_1_10',type:'fill-blank',diffLevel:1,instruction:'Complétez avec in, on ou at.',template:'I read ___ the evening.',answer:'in',hint:'in the morning/afternoon/evening',explanation:'"In the evening" — parties de la journée (sauf night).'},
  {id:'prep_1_11',type:'fill-blank',diffLevel:1,instruction:'Complétez avec in, on ou at.',template:'The shop is ___ the corner.',answer:'on',hint:'on the corner = au coin',explanation:'"On the corner" — expression fixe.'},
  {id:'prep_1_12',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['at','I','school','am','noon','at'],answer:'I am at school at noon.',hint:'at school, at noon',explanation:'"At school" (lieu) + "at noon" (heure).'},
  {id:'prep_1_13',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['on','She','her','the','birthday','July','is','in','3rd'],answer:'Her birthday is on July 3rd.',hint:'date précise → on',explanation:'"On July 3rd" — date précise.'},
  {id:'prep_1_14',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['The','book','on','is','table','the'],answer:'The book is on the table.',hint:'on = sur la surface',explanation:'"On the table" = sur la table.'},
  {id:'prep_1_15',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['in','was','born','1992','I'],answer:'I was born in 1992.',hint:'année → in',explanation:'"In 1992" — année.'},
  // Level 2 (+13)
  {id:'prep_2_01',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Je suis né(e) le 15 août.',answer:'I was born on August 15th.',alternatives:['I was born on the 15th of August.'],hint:'date précise → on',explanation:'"On August 15th" — date précise.'},
  {id:'prep_2_02',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Elle habite à Antananarivo depuis 2010.',answer:'She has lived in Antananarivo since 2010.',alternatives:['She has been in Antananarivo since 2010.'],hint:'depuis → since + date précise',explanation:'"Since" = depuis un moment précis.'},
  {id:'prep_2_03',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Le bus part à 7h30 le matin.',answer:'The bus leaves at 7:30 in the morning.',alternatives:['The bus departs at 7:30 am.'],hint:'heure → at ; matin → in the morning',explanation:'"At 7:30 in the morning".'},
  {id:'prep_2_04',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Il y a un marché tous les vendredis.',answer:'There is a market every Friday.',alternatives:['There is a market on Fridays.'],hint:'le vendredi → every Friday / on Fridays',explanation:'"Every Friday" ou "on Fridays".'},
  {id:'prep_2_05',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Nous nous retrouvons devant l\'école.',answer:'We meet in front of the school.',hint:'devant → in front of',explanation:'"In front of" = devant.'},
  {id:'prep_2_06',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'The meeting is on Friday at three.',answer:'The meeting is on Friday at three.',hint:'on Friday, at three',explanation:'"On Friday" (jour) + "at three" (heure).'},
  {id:'prep_2_07',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'I was born in the morning in summer.',answer:'I was born in the morning in summer.',hint:'in the morning, in summer',explanation:'"In the morning" + "in summer".'},
  {id:'prep_2_08',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'She lives near the market on Main Street.',answer:'She lives near the market on Main Street.',hint:'near, on',explanation:'"Near" = près de. "On Main Street".'},
  {id:'prep_2_09',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'I go to work by bus every morning.',answer:'I go to work by bus every morning.',hint:'by bus = en bus',explanation:'"By bus" = en bus.'},
  {id:'prep_2_10',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'The library is between the school and the park.',answer:'The library is between the school and the park.',hint:'between = entre',explanation:'"Between A and B" = entre A et B.'},
  {id:'prep_2_11',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['at','They','the','arrive','airport','at','noon'],answer:'They arrive at the airport at noon.',hint:'at the airport (lieu), at noon (heure)',explanation:'"At the airport" + "at noon".'},
  {id:'prep_2_12',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['on','I','walk','Sunday','mornings','to','church'],answer:'I walk to church on Sunday mornings.',hint:'on Sunday mornings',explanation:'"On Sunday mornings" — jour + partie du jour.'},
  {id:'prep_2_13',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['in','was','born','She','summer','in','1995'],answer:'She was born in summer in 1995.',hint:'in summer, in 1995',explanation:'"In summer" + "in 1995".'},
  {id:'prep_2_14',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['behind','The','garden','is','the','house'],answer:'The garden is behind the house.',hint:'behind = derrière',explanation:'"Behind" = derrière.'},
  {id:'prep_2_15',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['on','He','floor','lives','the','second'],answer:'He lives on the second floor.',hint:'on the second floor',explanation:'"On the second floor" — étages avec "on".'},
  // Level 3 (+13)
  {id:'prep_3_01',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'at',example:'I arrive at school at eight in the morning.',hint:'"at" pour heure ou lieu précis',explanation:'"At" = heure précise / lieu précis.'},
  {id:'prep_3_02',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'in front of',example:'I always wait in front of the school.',hint:'"in front of" = devant',explanation:'"In front of" = devant.'},
  {id:'prep_3_03',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'between',example:'The post office is between the bank and the park.',hint:'"between" = entre deux choses',explanation:'"Between A and B" = entre A et B.'},
  {id:'prep_3_04',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'by',example:'I go to school by bicycle.',hint:'"by" + moyen de transport',explanation:'"By bus/car/train" = en bus/voiture/train.'},
  {id:'prep_3_05',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'The party is in the night.',answer:'The party is at night.',hint:'at night (exception)',explanation:'"At night" — exception. Mais : "in the morning/evening".'},
  {id:'prep_3_06',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'I go to school in 7 am.',answer:'I go to school at 7 am.',hint:'heure précise → at',explanation:'"At 7 am" — heure précise.'},
  {id:'prep_3_07',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'She lives on Madagascar.',answer:'She lives in Madagascar.',hint:'pays → in',explanation:'"In Madagascar" — on dit "in" pour les pays.'},
  {id:'prep_3_08',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'We meet on the afternoon.',answer:'We meet in the afternoon.',hint:'in the afternoon',explanation:'"In the afternoon" — pas "on".'},
  {id:'prep_3_09',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'She was born on the 3rd of May.',answer:'Elle est née le 3 mai.',hint:'on the 3rd of May = le 3 mai',explanation:'"On the 3rd of May" = "le 3 mai".'},
  {id:'prep_3_10',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'The school is in front of the church.',answer:"L'école est en face de l'église.",alternatives:["L'école est devant l'église."],hint:'in front of = en face de / devant',explanation:'"In front of" = "devant" ou "en face de".'},
  {id:'prep_3_11',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'I will arrive at noon on Saturday.',answer:'J\'arriverai à midi samedi.',alternatives:["J'arriverai le samedi à midi."],hint:'at noon = à midi, on Saturday = samedi',explanation:'"At noon on Saturday".'},
  {id:'prep_3_12',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'The book is between the pen and the eraser.',answer:'Le livre est entre le stylo et la gomme.',hint:'between = entre',explanation:'"Between" = "entre".'},
  {id:'prep_3_13',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'I go to school by bus on weekdays.',question:'Comment va-t-il à l\'école ?',answer:'By bus.',alternatives:['He goes by bus.','On the bus.'],hint:'Écoutez le moyen de transport',explanation:'"By bus" = en bus.'},
  {id:'prep_3_14',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'The market is open on Fridays and Saturdays.',question:'Quand le marché est-il ouvert ?',answer:'On Fridays and Saturdays.',alternatives:['Friday and Saturday.','On Friday and Saturday.'],hint:'Écoutez les jours',explanation:'"On Fridays and Saturdays".'},
  {id:'prep_3_15',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'She lives near the lake between two mountains.',question:'Où habite-t-elle ?',answer:'Near the lake, between two mountains.',alternatives:['Between two mountains.','Near a lake.'],hint:'Écoutez les prépositions de lieu',explanation:'"Near the lake between two mountains".'}
);

// ─── QUESTIONS ───────────────────────────────────────────────────────────────
exercises.questions.push(
  // Level 1 (+12)
  {id:'q_1_01',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon mot interrogatif.',question:'___ do you live?',options:['What','Where','When','Who'],answer:'Where',hint:'pour un lieu',explanation:'"Where" = où.'},
  {id:'q_1_02',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon mot interrogatif.',question:'___ is your name?',options:['What','Where','When','Who'],answer:'What',hint:'pour une chose',explanation:'"What" = quoi/quel.'},
  {id:'q_1_03',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon mot interrogatif.',question:'___ is she?',options:['What','Where','When','Who'],answer:'Who',hint:'pour une personne',explanation:'"Who" = qui.'},
  {id:'q_1_04',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon mot interrogatif.',question:'___ do you go to school?',options:['What','Where','When','Who'],answer:'When',hint:'pour un moment',explanation:'"When" = quand.'},
  {id:'q_1_05',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'___ do you like coffee?',options:['What','Where','Why','Who'],answer:'Why',hint:'pour une raison',explanation:'"Why" = pourquoi.'},
  {id:'q_1_06',type:'multiple-choice',diffLevel:1,instruction:'Choisissez la bonne réponse.',question:'___ old are you?',options:['What','How','Who','Why'],answer:'How',hint:'"How" + adjectif',explanation:'"How old" = quel âge.'},
  {id:'q_1_07',type:'fill-blank',diffLevel:1,instruction:'Complétez la question.',template:'___ do you come from?',answer:'Where',hint:'lieu d\'origine',explanation:'"Where do you come from?" = D\'où viens-tu?'},
  {id:'q_1_08',type:'fill-blank',diffLevel:1,instruction:'Complétez la question.',template:'___ many students are in your class?',answer:'How',hint:'"How many" + dénombrable',explanation:'"How many" pour compter des objets dénombrables.'},
  {id:'q_1_09',type:'fill-blank',diffLevel:1,instruction:'Complétez la question.',template:'___ do you prefer, tea or coffee?',answer:'What',hint:'choix entre deux choses',explanation:'"What do you prefer?" = Que préfères-tu?'},
  {id:'q_1_10',type:'fill-blank',diffLevel:1,instruction:'Complétez la question.',template:'___ is your teacher\'s name?',answer:'What',hint:'pour un nom',explanation:'"What is your teacher\'s name?" = Quel est le nom de ton prof?'},
  {id:'q_1_11',type:'fill-blank',diffLevel:1,instruction:'Complétez la question.',template:'___ is your birthday?',answer:'When',hint:'pour une date',explanation:'"When is your birthday?" = C\'est quand ton anniversaire?'},
  {id:'q_1_12',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['you','do','live','Where','?'],answer:'Where do you live?',hint:'Where + do + sujet + verbe',explanation:'"Where do you live?" — mot interrogatif + auxiliaire + sujet + verbe.'},
  {id:'q_1_13',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['old','are','How','you','?'],answer:'How old are you?',hint:'"How old" + are + you',explanation:'"How old are you?" — question sur l\'âge.'},
  {id:'q_1_14',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['your','What','name','is','?'],answer:'What is your name?',hint:'What + is + sujet',explanation:'"What is your name?"'},
  {id:'q_1_15',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['do','Why','late','come','you','?'],answer:'Why do you come late?',hint:'Why + do + sujet + verbe',explanation:'"Why do you come late?" — raison.'},
  // Level 2 (+11)
  {id:'q_2_01',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Combien ça coûte ?',answer:'How much does it cost?',alternatives:['How much is it?'],hint:'"How much" pour un prix',explanation:'"How much" = combien (non-dénombrable / prix).'},
  {id:'q_2_02',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Pourquoi est-ce qu\'elle est en retard ?',answer:"Why is she late?",hint:'Why + auxiliaire + sujet',explanation:'"Why is she late?" — question directe.'},
  {id:'q_2_03',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Quand est-ce que le bus part ?',answer:'When does the bus leave?',alternatives:['When does the bus depart?'],hint:'"When does" + sujet + verbe',explanation:'"When does the bus leave?"'},
  {id:'q_2_04',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Qui a pris mon livre ?',answer:'Who took my book?',hint:'Who + verbe (pas d\'auxiliaire avec who sujet)',explanation:'"Who took my book?" — "who" est le sujet → pas de "did".'},
  {id:'q_2_05',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Comment s\'appelle ton professeur ?',answer:"What is your teacher's name?",alternatives:['What is the name of your teacher?'],hint:'What is...name?',explanation:'"What is your teacher\'s name?"'},
  {id:'q_2_06',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'Where do you come from?',answer:'Where do you come from?',hint:'Where + do + sujet',explanation:'"Where do you come from?" = D\'où viens-tu?'},
  {id:'q_2_07',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'How many brothers do you have?',answer:'How many brothers do you have?',hint:'"How many" + pluriel',explanation:'"How many brothers do you have?"'},
  {id:'q_2_08',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:"Why didn't you come to school yesterday?",answer:"Why didn't you come to school yesterday?",hint:'Why + didn\'t + sujet',explanation:'"Why didn\'t you come?" — négatif passé.'},
  {id:'q_2_09',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'What time does the train arrive?',answer:'What time does the train arrive?',hint:'"What time does" + sujet',explanation:'"What time does the train arrive?"'},
  {id:'q_2_10',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'Which book do you prefer?',answer:'Which book do you prefer?',hint:'Which = lequel',explanation:'"Which" = lequel (choix limité).'},
  {id:'q_2_11',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['does','what','do','she','?'],answer:'What does she do?',hint:'What + does + sujet + infinitif',explanation:'"What does she do?" — profession/activité.'},
  {id:'q_2_12',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['did','you','go','Where','yesterday','?'],answer:'Where did you go yesterday?',hint:'Where + did + sujet + infinitif',explanation:'"Where did you go yesterday?" — passé.'},
  {id:'q_2_13',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['does','cost','much','How','it','?'],answer:'How much does it cost?',hint:'"How much does" + sujet',explanation:'"How much does it cost?"'},
  {id:'q_2_14',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['is','Who','your','teacher','favourite','?'],answer:'Who is your favourite teacher?',hint:'Who + is',explanation:'"Who is your favourite teacher?"'},
  {id:'q_2_15',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['take','does','long','it','How','to','walk','school','to','?'],answer:'How long does it take to walk to school?',hint:'"How long does it take..."',explanation:'"How long does it take to...?" — durée.'},
  // Level 3 (+14)
  {id:'q_3_01',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'why',example:'Why do you like English?',hint:'"Why" = pourquoi',explanation:'"Why" introduit une question sur la raison.'},
  {id:'q_3_02',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'how many',example:'How many students are in your class?',hint:'"How many" + dénombrable',explanation:'"How many" pour les noms dénombrables.'},
  {id:'q_3_03',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'whose',example:'Whose book is this?',hint:'"Whose" = à qui',explanation:'"Whose" = à qui (possession).'},
  {id:'q_3_04',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'which',example:'Which colour do you prefer?',hint:'"Which" = lequel (choix limité)',explanation:'"Which" = lequel (choix limité).'},
  {id:'q_3_05',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'What she does for work?',answer:'What does she do for work?',hint:'does avant le sujet',explanation:'"What does she do?" — auxiliaire avant le sujet.'},
  {id:'q_3_06',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'Where you live?',answer:'Where do you live?',hint:'auxiliaire do requis',explanation:'"Where do you live?" — "do" requis avec les verbes ordinaires.'},
  {id:'q_3_07',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'Who did came to the party?',answer:'Who came to the party?',hint:'"Who" sujet → pas d\'auxiliaire',explanation:'"Who came?" — "who" est sujet → pas de "did".'},
  {id:'q_3_08',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'How much books do you have?',answer:'How many books do you have?',hint:'books = dénombrable → how many',explanation:'"How many" (dénombrable). "How much" (non-dénombrable).'},
  {id:'q_3_09',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'What time does the school start?',answer:'À quelle heure commence l\'école ?',hint:'What time = à quelle heure',explanation:'"What time" = "à quelle heure".'},
  {id:'q_3_10',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'How long have you been waiting?',answer:'Depuis combien de temps attends-tu ?',alternatives:['Depuis quand attends-tu ?'],hint:'How long = depuis combien de temps',explanation:'"How long have you been...?" = "Depuis combien de temps...?"'},
  {id:'q_3_11',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'Who told you that?',answer:'Qui t\'a dit ça ?',hint:'Who = qui',explanation:'"Who told you that?" = "Qui t\'a dit ça?"'},
  {id:'q_3_12',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'Which way should I go?',answer:'Par quel chemin dois-je aller ?',alternatives:['Quel chemin dois-je prendre ?'],hint:'which way = par quel chemin',explanation:'"Which way" = "par quel chemin/quelle direction".'},
  {id:'q_3_13',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'Where do you come from? I come from Madagascar.',question:'D\'où vient la personne ?',answer:'From Madagascar.',alternatives:['Madagascar.','She comes from Madagascar.'],hint:'Écoutez la réponse',explanation:'"I come from Madagascar."'},
  {id:'q_3_14',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'How many languages do you speak? I speak three languages.',question:'Combien de langues parle-t-il ?',answer:'Three.',alternatives:['Three languages.','He speaks three.'],hint:'Écoutez le nombre',explanation:'"I speak three languages."'},
  {id:'q_3_15',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'Why are you late? Because the bus was delayed.',question:'Pourquoi est-il en retard ?',answer:'Because the bus was delayed.',alternatives:['The bus was late.','The bus was delayed.'],hint:'Écoutez la raison',explanation:'"Because the bus was delayed."'}
);

// ─── MODALS ──────────────────────────────────────────────────────────────────
exercises.modals.push(
  // Level 1 (+15)
  {id:'mod_1_01',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon modal.',question:'She ___ swim very well.',options:['can','must','should','have'],answer:'can',hint:'capacité → can',explanation:'"Can" = capacité.'},
  {id:'mod_1_02',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon modal.',question:'You ___ eat more vegetables.',options:['can','must','should','will'],answer:'should',hint:'conseil → should',explanation:'"Should" = conseil.'},
  {id:'mod_1_03',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon modal.',question:'You ___ wear a seatbelt. It\'s the law.',options:['can','must','should','might'],answer:'must',hint:'obligation forte → must',explanation:'"Must" = obligation forte.'},
  {id:'mod_1_04',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon modal.',question:'It ___ rain tomorrow. The sky is cloudy.',options:['must','should','might','can'],answer:'might',hint:'possibilité incertaine → might',explanation:'"Might" = possibilité incertaine.'},
  {id:'mod_1_05',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon modal.',question:'___ you help me, please?',options:['Can','Must','Should','Might'],answer:'Can',hint:'demande polie → can',explanation:'"Can you help me?" = demande polie.'},
  {id:'mod_1_06',type:'multiple-choice',diffLevel:1,instruction:'Choisissez le bon modal.',question:'You ___ enter — it\'s private.',options:['must','can\'t','should','might'],answer:"can't",hint:'interdiction → can\'t',explanation:'"Can\'t" = interdiction.'},
  {id:'mod_1_07',type:'fill-blank',diffLevel:1,instruction:"Complétez avec can ou can't.",template:'He ___ drive yet — he is only 15.',answer:"can't",hint:'15 ans → trop jeune',explanation:'"Can\'t drive" — trop jeune.'},
  {id:'mod_1_08',type:'fill-blank',diffLevel:1,instruction:"Complétez avec should ou shouldn't.",template:'You ___ stay up too late. You have school tomorrow.',answer:"shouldn't",hint:'mauvais conseil → shouldn\'t',explanation:'"Shouldn\'t" = ne devrait pas (conseil négatif).'},
  {id:'mod_1_09',type:'fill-blank',diffLevel:1,instruction:"Complétez avec must ou mustn't.",template:'You ___ touch that wire — it is dangerous.',answer:"mustn't",hint:'danger → mustn\'t',explanation:'"Mustn\'t" = interdiction absolue (danger).'},
  {id:'mod_1_10',type:'fill-blank',diffLevel:1,instruction:"Complétez avec will ou would.",template:'___ you like some tea?',answer:'Would',hint:'offre polie → would',explanation:'"Would you like...?" = offre polie.'},
  {id:'mod_1_11',type:'fill-blank',diffLevel:1,instruction:"Complétez avec may ou might.",template:'She ___ be at the market — I\'m not sure.',answer:'might',alternatives:['may'],hint:'incertitude → might/may',explanation:'"Might/may" = peut-être.'},
  {id:'mod_1_12',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['can','She','English','speak'],answer:'She can speak English.',hint:'can + infinitif (sans to)',explanation:'"Can" + infinitif.'},
  {id:'mod_1_13',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['should','more','You','exercise'],answer:'You should exercise more.',hint:'should + infinitif',explanation:'"Should" + infinitif.'},
  {id:'mod_1_14',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['here','must','You','on','be','time'],answer:'You must be here on time.',hint:'must + infinitif',explanation:'"Must" + infinitif.'},
  {id:'mod_1_15',type:'word-order',diffLevel:1,instruction:'Mettez dans le bon ordre.',words:['help','Could','please','you','me','?'],answer:'Could you help me please?',hint:'Could = can poli',explanation:'"Could you...?" = demande polie.'},
  // Level 2 (+11)
  {id:'mod_2_01',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Elle sait parler trois langues.',answer:'She can speak three languages.',alternatives:['She is able to speak three languages.'],hint:'savoir → can',explanation:'"Can" = savoir/pouvoir.'},
  {id:'mod_2_02',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Tu ne devrais pas manger autant de sucre.',answer:"You shouldn't eat so much sugar.",alternatives:["You should not eat so much sugar."],hint:'conseil négatif → shouldn\'t',explanation:'"Shouldn\'t" = ne devrait pas.'},
  {id:'mod_2_03',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Il doit finir ses devoirs avant dîner.',answer:'He must finish his homework before dinner.',alternatives:['He has to finish his homework before dinner.'],hint:'obligation → must / have to',explanation:'"Must/have to" = obligation.'},
  {id:'mod_2_04',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Puis-je aller aux toilettes ?',answer:'May I go to the toilet?',alternatives:['Can I go to the toilet?'],hint:'permission → may/can',explanation:'"May I...?" = permission (formel).'},
  {id:'mod_2_05',type:'translate',diffLevel:2,instruction:'Traduisez en anglais.',french:'Il se pourrait qu\'il pleuve ce soir.',answer:'It might rain this evening.',alternatives:['It may rain this evening.'],hint:'possibilité → might/may',explanation:'"Might/may" = possibilité.'},
  {id:'mod_2_06',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'You should drink more water every day.',answer:'You should drink more water every day.',hint:'should + infinitif',explanation:'"Should drink" = conseil.'},
  {id:'mod_2_07',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'Can you close the window please?',answer:'Can you close the window please?',hint:'Can = capacité/demande',explanation:'"Can you...?" = demande polie.'},
  {id:'mod_2_08',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'You must not smoke inside the building.',answer:'You must not smoke inside the building.',hint:'must not = interdiction',explanation:'"Must not" = interdiction.'},
  {id:'mod_2_09',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'She might come to the party tonight.',answer:'She might come to the party tonight.',hint:'might = peut-être',explanation:'"Might come" = possibilité.'},
  {id:'mod_2_10',type:'listening',diffLevel:2,instruction:'Écoutez et écrivez ce que vous entendez.',audio:'Would you like some coffee or tea?',answer:'Would you like some coffee or tea?',hint:'Would = offre polie',explanation:'"Would you like...?" = offre polie.'},
  {id:'mod_2_11',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['could','you','the','door','Could','open','?'],answer:'Could you open the door?',hint:'Could = can poli',explanation:'"Could you open...?" = demande polie.'},
  {id:'mod_2_12',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['must','passport','You','your','carry'],answer:'You must carry your passport.',hint:'must + infinitif',explanation:'"Must carry" = obligation.'},
  {id:'mod_2_13',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['might','late','be','She'],answer:'She might be late.',hint:'might + infinitif',explanation:'"Might be" = possibilité.'},
  {id:'mod_2_14',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['not','You','here','mustn\'t','smoke'],answer:"You mustn't smoke here.",hint:"mustn't + infinitif",explanation:'"Mustn\'t smoke" = interdiction.'},
  {id:'mod_2_15',type:'word-order',diffLevel:2,instruction:'Mettez dans le bon ordre.',words:['can','you','fast','How','run','?'],answer:'How fast can you run?',hint:'How + modal + sujet + infinitif',explanation:'"How fast can you run?"'},
  // Level 3 (+11)
  {id:'mod_3_01',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'should',example:'You should study every evening.',hint:'"should" = conseil',explanation:'"Should" = conseil / recommandation.'},
  {id:'mod_3_02',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'might',example:'It might snow tomorrow.',hint:'"might" = possibilité incertaine',explanation:'"Might" = peut-être.'},
  {id:'mod_3_03',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'must',example:'You must arrive on time.',hint:'"must" = obligation forte',explanation:'"Must" = obligation.'},
  {id:'mod_3_04',type:'free-production',diffLevel:3,instruction:'Écris une phrase avec le mot donné.',keyword:'could',example:'Could you pass me the salt?',hint:'"could" = demande polie ou capacité passée',explanation:'"Could" = polie ou passé de "can".'},
  {id:'mod_3_05',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'She can to sing very well.',answer:'She can sing very well.',hint:'modal → pas de "to"',explanation:'Après les modaux : infinitif SANS "to".'},
  {id:'mod_3_06',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'You must to wear a seatbelt.',answer:'You must wear a seatbelt.',hint:'must → pas de "to"',explanation:'"Must wear" — pas de "to" après les modaux.'},
  {id:'mod_3_07',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'He musts leave now.',answer:'He must leave now.',hint:'modaux invariables — jamais de -s',explanation:'"Must" = invariable.'},
  {id:'mod_3_08',type:'error-correct',diffLevel:3,instruction:"Corrigez l'erreur.",sentence:'Should I to bring anything?',answer:'Should I bring anything?',hint:'should → pas de "to"',explanation:'"Should I bring?" — pas de "to".'},
  {id:'mod_3_09',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'You should see a doctor.',answer:'Tu devrais voir un médecin.',hint:'should = devrais',explanation:'"Should" = "devrait/devrais".'},
  {id:'mod_3_10',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'She can speak English and French.',answer:'Elle parle (sait parler) anglais et français.',hint:'can speak = sait parler',explanation:'"Can speak" = "sait parler".'},
  {id:'mod_3_11',type:'translate-fr',diffLevel:3,instruction:'Traduisez en français.',english:'You must not enter without permission.',answer:'Tu ne dois pas entrer sans permission.',hint:'must not = ne doit pas',explanation:'"Must not" = interdiction.'},
  {id:'mod_3_12',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'You should eat vegetables and you must drink water.',question:'Quel modal exprime une obligation ?',answer:'must',alternatives:['Must.'],hint:'conseil vs obligation',explanation:'"Should" = conseil. "Must" = obligation.'},
  {id:'mod_3_13',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'Can you ride a bicycle? Yes, I can.',question:'La personne peut-elle faire du vélo ?',answer:'Yes, she can.',alternatives:['Yes.','Yes, he can.'],hint:'Écoutez la réponse',explanation:'"Yes, I can" = oui, je peux.'},
  {id:'mod_3_14',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:'It might rain this afternoon so you should take an umbrella.',question:'Que conseille-t-on de prendre ?',answer:'An umbrella.',alternatives:['umbrella','A umbrella.'],hint:'Écoutez la recommandation',explanation:'"Take an umbrella" = prendre un parapluie.'},
  {id:'mod_3_15',type:'listening-comp',diffLevel:3,instruction:'Écoutez et répondez à la question.',audio:"You mustn't use your phone in class.",question:'Que ne peut-on pas faire en classe ?',answer:'Use a phone.',alternatives:['Use your phone.','Use the phone.'],hint:'Écoutez l\'interdiction',explanation:'"Mustn\'t use your phone in class".'}
);
"""

with open(EXERCISES_PATH, encoding='utf-8') as f:
    src = f.read()

insert_pos = src.index('export function getAllExercises()')
new_src = src[:insert_pos] + NEW + '\n' + src[insert_pos:]

with open(EXERCISES_PATH, 'w', encoding='utf-8') as f:
    f.write(new_src)

print('Batch 1 done: articles, plurals, therebeis, prepositions, questions, modals')
