"""
Add TASK 2 (sinceFor, usedTo, verbsOfState) + TASK 3 (adjectives grammar section)
to theory.js and exercises.js.
"""
import sys, os, re
sys.stdout.reconfigure(encoding='utf-8')

BASE = os.path.join(os.path.dirname(__file__), '..')
THEORY_PATH   = os.path.join(BASE, 'src', 'data', 'theory.js')
EXERCISES_PATH = os.path.join(BASE, 'src', 'data', 'exercises.js')

# ─────────────────────────────────────────────────────────────────────────────
# 1. THEORY sections to add (inserted before `export const theoryTopics`)
# ─────────────────────────────────────────────────────────────────────────────
NEW_THEORY = r"""
  sinceFor: {
    id: 'sinceFor',
    title: 'Since & For',
    icon: '⏳',
    level: 'B1',
    subtitle: 'Exprimer la durée et le point de départ',
    malgasyNote: 'Manazava ny faharetan\'ny zavatra sy ny fotoana nanombohan\'ny',
    sections: [
      {
        title: '📍 Since — point de départ précis',
        content: '<strong>Since</strong> + moment précis (date, événement). La durée a commencé à ce moment.',
        examples: [
          { en: 'I have lived here <strong>since 2015</strong>.', fr: 'J\'habite ici depuis 2015.' },
          { en: 'She has been working <strong>since Monday</strong>.', fr: 'Elle travaille depuis lundi.' },
          { en: 'We haven\'t spoken <strong>since the argument</strong>.', fr: 'Nous ne nous sommes pas parlé depuis la dispute.' },
        ]
      },
      {
        title: '⏱️ For — durée (période)',
        content: '<strong>For</strong> + durée (nombre de jours, mois, années, heures...)',
        examples: [
          { en: 'I have lived here <strong>for five years</strong>.', fr: 'J\'habite ici depuis cinq ans.' },
          { en: 'She has been waiting <strong>for two hours</strong>.', fr: 'Elle attend depuis deux heures.' },
          { en: 'He studied English <strong>for ten years</strong>.', fr: 'Il a étudié l\'anglais pendant dix ans.' },
        ]
      },
      {
        title: '🔗 Avec quel temps ?',
        content: '<strong>Present Perfect</strong> pour la durée jusqu\'au présent. <strong>Past Perfect</strong> pour la durée avant un moment passé.',
        examples: [
          { en: 'I <strong>have known</strong> her for three years. (jusqu\'à maintenant)', fr: 'Je la connais depuis trois ans.' },
          { en: 'He <strong>had worked</strong> there for 20 years before retiring.', fr: 'Il avait travaillé là-bas pendant 20 ans avant de partir à la retraite.' },
        ]
      },
      {
        title: '⚠️ Erreurs courantes',
        content: 'Confusions fréquentes à éviter',
        examples: [
          { en: '❌ I live here since 5 years.', fr: '→ Wrong: "since" + durée est incorrect' },
          { en: '✅ I have lived here for 5 years. / since 2019.', fr: 'Correct !' },
          { en: '❌ I haven\'t seen her since three weeks.', fr: '→ "since" + point précis, pas durée' },
          { en: '✅ I haven\'t seen her for three weeks.', fr: 'Correct !' },
        ]
      },
    ],
    tips: [
      '🔑 Since + moment précis : since 2010, since Monday, since she left',
      '🔑 For + durée : for 5 years, for a long time, for two months',
      '💡 Question : How long have you...? → réponse avec "for" ou "since"',
      '⚠️ "For" peut aussi s\'utiliser avec le Past Simple (action terminée) : He worked there for 10 years.',
    ]
  },

  usedTo: {
    id: 'usedTo',
    title: 'Used to',
    icon: '🔙',
    level: 'B1',
    subtitle: 'Les habitudes et états passés qui n\'existent plus',
    malgasyNote: 'Ny zava-mahazatra tamin\'ny lasa izay tsy misy intsony',
    sections: [
      {
        title: '✅ Forme affirmative',
        content: 'Sujet + <strong>used to</strong> + verbe infinitif',
        examples: [
          { en: 'I <strong>used to</strong> walk to school.', fr: 'J\'allais à l\'école à pied (avant, plus maintenant).' },
          { en: 'She <strong>used to</strong> love dancing.', fr: 'Elle aimait danser (avant).' },
          { en: 'They <strong>used to</strong> live in the countryside.', fr: 'Ils habitaient à la campagne (avant).' },
        ]
      },
      {
        title: '❌ Forme négative',
        content: 'Sujet + <strong>didn\'t use to</strong> + verbe infinitif',
        examples: [
          { en: 'I <strong>didn\'t use to</strong> like vegetables.', fr: 'Je n\'aimais pas les légumes (avant).' },
          { en: 'He <strong>didn\'t use to</strong> work this hard.', fr: 'Il ne travaillait pas autant (avant).' },
        ]
      },
      {
        title: '❓ Forme interrogative',
        content: '<strong>Did</strong> + sujet + <strong>use to</strong> + verbe ?',
        examples: [
          { en: '<strong>Did</strong> you <strong>use to</strong> play football?', fr: 'Est-ce que tu jouais au football (avant) ?' },
          { en: '<strong>Did</strong> she <strong>use to</strong> live here?', fr: 'Est-ce qu\'elle habitait ici (avant) ?' },
        ]
      },
      {
        title: '⚠️ Ne pas confondre avec "be/get used to"',
        content: '<strong>Be/Get used to</strong> + gérondif = être/s\'habituer à (présent)',
        examples: [
          { en: 'I <strong>am used to</strong> waking up early. (j\'en ai l\'habitude)', fr: 'J\'ai l\'habitude de me lever tôt.' },
          { en: 'She is <strong>getting used to</strong> the cold weather.', fr: 'Elle s\'habitue au temps froid.' },
          { en: '⚠️ "used to work" ≠ "used to working"', fr: 'Habitude passée ≠ être habitué à' },
        ]
      },
      {
        title: '🔄 Would pour les habitudes passées',
        content: '<strong>Would</strong> peut remplacer "used to" pour les habitudes (pas les états)',
        examples: [
          { en: 'We <strong>would</strong> go to the beach every summer.', fr: 'Nous allions à la plage chaque été.' },
          { en: '✅ She used to be shy. (état → "used to" only)', fr: 'Elle était timide (avant).' },
          { en: '❌ She would be shy. (wrong for states)', fr: 'Incorrect pour les états.' },
        ]
      },
    ],
    tips: [
      '🔑 Used to = habitude OU état passé qui n\'existe plus',
      '🔑 Would = habitude passée SEULEMENT (pas les états)',
      '⚠️ "Be used to + -ing" = être habitué à (présent)',
      '💡 Pas de "used to" au présent : on dit "usually" → I usually walk to work.',
    ]
  },

  verbsOfState: {
    id: 'verbsOfState',
    title: 'Verbes + Gérondif ou Infinitif',
    icon: '🎯',
    level: 'B1',
    subtitle: 'Like, love, hate, enjoy, prefer — gérondif ou infinitif ?',
    malgasyNote: 'Matoanteny + -ing na + infinitif',
    sections: [
      {
        title: '✅ Verbes suivis du gérondif SEULEMENT',
        content: 'Ces verbes exigent toujours le gérondif (-ing)',
        examples: [
          { en: 'I <strong>enjoy</strong> reading books.', fr: 'J\'aime lire des livres.' },
          { en: 'She <strong>doesn\'t mind</strong> waiting.', fr: 'Ça ne la dérange pas d\'attendre.' },
          { en: 'He <strong>keeps</strong> talking during class.', fr: 'Il n\'arrête pas de parler en classe.' },
          { en: 'They <strong>finished</strong> eating and left.', fr: 'Ils ont fini de manger et sont partis.' },
          { en: 'I <strong>avoid</strong> driving at night.', fr: 'J\'évite de conduire la nuit.' },
        ]
      },
      {
        title: '✅ Verbes suivis de l\'infinitif SEULEMENT',
        content: 'Ces verbes exigent toujours l\'infinitif (to + verbe)',
        examples: [
          { en: 'She <strong>wants</strong> to learn English.', fr: 'Elle veut apprendre l\'anglais.' },
          { en: 'He <strong>decided</strong> to leave early.', fr: 'Il a décidé de partir tôt.' },
          { en: 'They <strong>hope</strong> to visit Paris.', fr: 'Ils espèrent visiter Paris.' },
          { en: 'I <strong>need</strong> to study more.', fr: 'J\'ai besoin d\'étudier plus.' },
        ]
      },
      {
        title: '🔄 Verbes suivis des DEUX (sens identique)',
        content: 'Like, love, hate, prefer → gérondif ou infinitif, même sens',
        examples: [
          { en: 'I <strong>like swimming</strong>. = I <strong>like to swim</strong>.', fr: 'J\'aime nager.' },
          { en: 'She <strong>loves cooking</strong>. = She <strong>loves to cook</strong>.', fr: 'Elle aime cuisiner.' },
          { en: 'He <strong>hates waiting</strong>. = He <strong>hates to wait</strong>.', fr: 'Il déteste attendre.' },
        ]
      },
      {
        title: '⚠️ Stop + gérondif vs infinitif (sens différent !)',
        content: 'Le sens change selon la forme utilisée',
        examples: [
          { en: 'He <strong>stopped smoking</strong>. (arrêter de fumer)', fr: 'Il a arrêté de fumer.' },
          { en: 'He <strong>stopped to smoke</strong>. (s\'arrêter pour fumer)', fr: 'Il s\'est arrêté pour fumer.' },
          { en: 'She <strong>remembered calling</strong> him. (se souvenir d\'avoir appelé)', fr: 'Elle se souvient de lui avoir téléphoné.' },
          { en: 'She <strong>remembered to call</strong> him. (se souvenir de devoir appeler)', fr: 'Elle a pensé à lui téléphoner.' },
        ]
      },
    ],
    tips: [
      '🔑 enjoy, mind, avoid, finish, keep → toujours + -ing',
      '🔑 want, need, decide, hope, plan → toujours + infinitif',
      '🔄 like, love, hate, prefer → -ing ou infinitif (même sens)',
      '⚠️ stop, try, remember, forget → sens DIFFÉRENT selon -ing ou infinitif',
    ]
  },

  adjectives: {
    id: 'adjectives',
    title: 'Les Adjectifs',
    icon: '✨',
    level: 'A1–A2',
    subtitle: 'Qualifier les personnes et les choses',
    malgasyNote: 'Teny mpamaritra anarana',
    sections: [
      {
        title: '📌 Position de l\'adjectif',
        content: 'En anglais, l\'adjectif se place <strong>avant</strong> le nom (≠ français)',
        examples: [
          { en: 'a <strong>beautiful</strong> house (≠ une maison belle)', fr: 'une belle maison' },
          { en: 'a <strong>tall</strong> student', fr: 'un grand étudiant' },
          { en: 'She is <strong>happy</strong>. (après "be")', fr: 'Elle est heureuse.' },
        ]
      },
      {
        title: '👆 Adjectifs démonstratifs',
        content: 'Indiquent la proximité ou l\'éloignement',
        examples: [
          { en: '<strong>This</strong> book (ce livre-ci — proche, singulier)', fr: 'ce livre-ci' },
          { en: '<strong>That</strong> house (cette maison-là — loin, singulier)', fr: 'cette maison-là' },
          { en: '<strong>These</strong> shoes (ces chaussures-ci — proche, pluriel)', fr: 'ces chaussures-ci' },
          { en: '<strong>Those</strong> trees (ces arbres-là — loin, pluriel)', fr: 'ces arbres-là' },
        ]
      },
      {
        title: '📋 Ordre des adjectifs multiples',
        content: 'Quand il y a plusieurs adjectifs : opinion → taille → âge → forme → couleur → origine → matière',
        examples: [
          { en: 'a <strong>beautiful big old round green French</strong> vase', fr: 'un beau grand vieux vase rond vert français' },
          { en: 'a <strong>lovely small</strong> dog', fr: 'un joli petit chien' },
          { en: 'a <strong>tall young</strong> man', fr: 'un grand jeune homme' },
        ]
      },
      {
        title: '⚡ Adjectifs courants à mémoriser',
        content: 'Adjectifs essentiels avec leur contraire',
        examples: [
          { en: 'big ↔ small | tall ↔ short | young ↔ old', fr: 'grand ↔ petit | grand ↔ court | jeune ↔ vieux' },
          { en: 'happy ↔ sad | hot ↔ cold | fast ↔ slow', fr: 'heureux ↔ triste | chaud ↔ froid | rapide ↔ lent' },
          { en: 'easy ↔ difficult | cheap ↔ expensive | clean ↔ dirty', fr: 'facile ↔ difficile | bon marché ↔ cher | propre ↔ sale' },
        ]
      },
      {
        title: '🔄 Adjectif ≠ Adverbe',
        content: 'L\'adjectif qualifie un nom, l\'adverbe qualifie un verbe',
        examples: [
          { en: 'She is a <strong>quick</strong> runner. (adjectif → runner)', fr: 'C\'est une coureuse rapide.' },
          { en: 'She runs <strong>quickly</strong>. (adverbe → runs)', fr: 'Elle court rapidement.' },
          { en: 'He is <strong>careful</strong>. (adjectif après "be")', fr: 'Il est prudent.' },
          { en: 'He drives <strong>carefully</strong>. (adverbe)', fr: 'Il conduit prudemment.' },
        ]
      },
    ],
    tips: [
      '🔑 Adjectifs en anglais : invariables (pas de -s au pluriel)',
      '🔑 Toujours avant le nom : a red car (pas a car red)',
      '⚠️ Démonstratifs : this/that (singulier) — these/those (pluriel)',
      '💡 Ordre : "a lovely little old rectangular green French silver whittling knife"',
    ]
  },

"""

# ─────────────────────────────────────────────────────────────────────────────
# 2. theoryTopics entries to add (before the closing `];`)
# ─────────────────────────────────────────────────────────────────────────────
NEW_THEORY_TOPICS = """
  // ── A1–A2 (new) ──────────────────────────────────────────────────────────
  { id: 'adjectives',    label: 'Les Adjectifs',                      icon: '✨',   level: 'A1–A2' },
  // ── B1 (new) ─────────────────────────────────────────────────────────────
  { id: 'sinceFor',      label: 'Since & For',                        icon: '⏳',   level: 'B1' },
  { id: 'usedTo',        label: 'Used to',                            icon: '🔙',   level: 'B1' },
  { id: 'verbsOfState',  label: 'Verbes + Gérondif / Infinitif',      icon: '🎯',   level: 'B1' },"""

# ─────────────────────────────────────────────────────────────────────────────
# 3. malgasyManual entries (Boky chapters)
# ─────────────────────────────────────────────────────────────────────────────
NEW_BOKY = r"""
  {
    id: 'mg_adjectives',
    grammarRef: 'adjectives',
    title: 'Adjectives',
    titleMg: 'Teny Mpamaritra',
    icon: '✨',
    level: 'A1–A2',
    explanation: 'Ny teny mpamaritra (adjectives) dia mamaritra ny anarana. Amin\'ny teny anglisy, ny teny mpamaritra dia apetraka ALOHAN\'ny anarana (tsy toy ny teny frantsay). Ny teny malagasy kosa dia matetika mametraka ny mpamaritra AORIAN\'ny anarana.',
    rows: [
      {
        label: 'Toerana (Position)',
        structure: 'adjectif + nom',
        example_en: 'a beautiful house',
        example_mg: 'trano tsara',
        note: 'Anglisy: adjective ALOHAN\'ny noun | Malagasy: aorian\'ny noun matetika',
      },
      {
        label: 'Démonstratifs (Mampiseho)',
        structure: 'this/that (sg) | these/those (pl)',
        example_en: 'this book / those trees',
        example_mg: 'ity boky ity / ireny hazo ireny',
        note: 'this/these = akaiky | that/those = lavitra',
      },
      {
        label: 'Mifanohitra (Opposés)',
        structure: 'big ↔ small | happy ↔ sad',
        example_en: 'big house / small house',
        example_mg: 'trano lehibe / trano kely',
        note: 'Ny adjectives dia tsy miova ho an\'ny pluriel amin\'ny anglisy',
      },
    ],
    tipsMg: [
      'Amin\'ny anglisy ny mpamaritra dia tsy manova endrika (tsy misy -s)',
      'Filaharan\'ny mpamaritra maro: hevitra → haben\'ny → taona → endrika → loko → niaviana → zavatra',
      'Aorian\'ny "be": She is happy (adjective aorian\'ny be)',
    ],
  },

  {
    id: 'mg_sinceFor',
    grammarRef: 'sinceFor',
    title: 'Since & For',
    titleMg: 'Since sy For',
    icon: '⏳',
    level: 'B1',
    explanation: 'Ny "since" sy "for" dia ampiasaina miaraka amin\'ny Present Perfect na Past Perfect hanazavana ny faharetan\'ny zavatra. "Since" = nanomboka rahoviana | "For" = nandritra ny fotoana maharitra.',
    rows: [
      {
        label: 'Since (nanomboka)',
        structure: 'since + fotoana manokana',
        example_en: 'I have lived here since 2015.',
        example_mg: 'Monina eto aho nanomboka ny 2015.',
        note: 'since + taona, andro, fotoana manokana',
      },
      {
        label: 'For (nandritra)',
        structure: 'for + faharetan\'ny fotoana',
        example_en: 'I have lived here for five years.',
        example_mg: 'Monina eto aho nandritra ny dimy taona.',
        note: 'for + isa + fotoana (hours, days, years)',
      },
      {
        label: 'Fanontaniana (Question)',
        structure: 'How long have you...?',
        example_en: 'How long have you studied English?',
        example_mg: 'Hatriniry no nianarànao anglisy?',
        note: '"How long" + Present Perfect → valiny: for / since',
      },
    ],
    tipsMg: [
      'Since = nanomboka fotoana iray manokana (2015, Monday, last year)',
      'For = nandritra ny fotoana iray (5 years, two months, a long time)',
      'Tsy maintsy ampiasaina miaraka amin\'ny Present Perfect na Past Perfect',
    ],
  },

  {
    id: 'mg_usedTo',
    grammarRef: 'usedTo',
    title: 'Used to',
    titleMg: 'Used to — Fomba Lasa',
    icon: '🔙',
    level: 'B1',
    explanation: 'Ny "used to" dia ampiasaina hilazana ny fomba na toe-javatra tamin\'ny lasa izay tsy misy intsony ankehitriny. Ny malagasy dia mahazo mampiasa "fahiny" na "taloha" hilazana izany.',
    rows: [
      {
        label: 'Fomba fanaovana (+)',
        structure: 'sujet + used to + verbe',
        example_en: 'I used to walk to school.',
        example_mg: 'Nandeha tongotra ho any an-tsekoly aho fahiny.',
        note: 'Fomba na toe-javatra tamin\'ny lasa, tsy misy intsony',
      },
      {
        label: 'Fandavana (−)',
        structure: 'sujet + didn\'t use to + verbe',
        example_en: 'I didn\'t use to like vegetables.',
        example_mg: 'Tsy tia legioma aho fahiny.',
        note: 'didn\'t use to (tsy "used")',
      },
      {
        label: 'Fanontaniana (?)',
        structure: 'Did + sujet + use to + verbe?',
        example_en: 'Did you use to play football?',
        example_mg: 'Nilalao baolina-kitra ve ianao fahiny?',
        note: 'use to (tsy "used") aorian\'ny "did"',
      },
    ],
    tipsMg: [
      'Used to ≠ be used to: "I used to swim" (lasa) ≠ "I am used to swimming" (zatra)',
      'Would koa azo ampiasaina ho an\'ny fomba lasa, fa tsy ho an\'ny toe-javatra (state)',
      'Tsy misy "use to" amin\'ny ankehitriny — ampiasao "usually"',
    ],
  },

  {
    id: 'mg_verbsOfState',
    grammarRef: 'verbsOfState',
    title: 'Verbes + -ing / Infinitif',
    titleMg: 'Matoanteny + -ing na Infinitif',
    icon: '🎯',
    level: 'B1',
    explanation: 'Ny matoanteny sasany dia mahazo miaraka amin\'ny gérondif (-ing) ihany, ny hafa dia miaraka amin\'ny infinitif (to + verbe), ary ny hafa kosa dia miaraka amin\'ny roa. Ilaina ny mahafantatra izay manaraka izay.',
    rows: [
      {
        label: '-ing ihany',
        structure: 'enjoy/mind/avoid/finish + -ing',
        example_en: 'I enjoy reading. / She avoids driving.',
        example_mg: 'Tia mamaky aho. / Menatra mitaingina fiara izy.',
        note: 'enjoy, mind, avoid, finish, keep, consider → -ing ihany',
      },
      {
        label: 'Infinitif ihany',
        structure: 'want/need/decide/hope + to + verbe',
        example_en: 'She wants to leave. / He decided to stay.',
        example_mg: 'Te-handeha izy. / Nifidy ny hitoetra izy.',
        note: 'want, need, decide, hope, plan, promise → infinitif ihany',
      },
      {
        label: 'Roa azo (sens mitovy)',
        structure: 'like/love/hate/prefer + -ing NA infinitif',
        example_en: 'I like swimming. = I like to swim.',
        example_mg: 'Tia milomano aho.',
        note: 'like, love, hate, prefer → roa azo, sens mitovy',
      },
    ],
    tipsMg: [
      'Stop + -ing = mitsahatra: He stopped smoking (najanony ny fisotro sigara)',
      'Stop + infinitif = mijanona mba hanao: He stopped to smoke (nijanonan\'izy mba hisotro sigara)',
      'Remember + -ing = mahatsiaro nataony | Remember + infinitif = mahatsiaro hataony',
    ],
  },

"""

# ─────────────────────────────────────────────────────────────────────────────
# 4. Exercises for new sections (sf_, ut_, vs_, adj_)
# ─────────────────────────────────────────────────────────────────────────────
NEW_EXERCISES = r"""
// ═══════════════════════════════════════════════════════════════
// NEW SECTIONS — sinceFor, usedTo, verbsOfState, adjectives
// ═══════════════════════════════════════════════════════════════

exercises.sinceFor = [
  // L1 — 12 exercises
  {id:'sf_1_01',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'I have lived in this city ___ 2018.',
   options:['since','for','during','from'],answer:'since',
   hint:'"2018" est un point précis dans le temps',explanation:'"Since" + point de départ précis (année, date, moment).'},
  {id:'sf_1_02',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'She has been learning English ___ three years.',
   options:['since','for','from','during'],answer:'for',
   hint:'"three years" = une durée',explanation:'"For" + durée (nombre d\'années, mois, heures...).'},
  {id:'sf_1_03',type:'fill-blank',diffLevel:1,
   instruction:'Complétez avec since ou for.',
   template:'We haven\'t eaten ___ this morning.',
   answer:'since',verbHint:'since/for',
   hint:'"this morning" est un moment précis',explanation:'"Since" + moment précis (this morning, last Monday, 2020).'},
  {id:'sf_1_04',type:'fill-blank',diffLevel:1,
   instruction:'Complétez avec since ou for.',
   template:'He has been waiting ___ two hours.',
   answer:'for',verbHint:'since/for',
   hint:'"two hours" = durée',explanation:'"For" + durée chiffrée.'},
  {id:'sf_1_05',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'They have been friends ___ they were children.',
   options:['since','for','during','in'],answer:'since',
   hint:'"since" + événement passé (they were children)',explanation:'"Since" peut être suivi d\'une proposition (since + sujet + verbe).'},
  {id:'sf_1_06',type:'fill-blank',diffLevel:1,
   instruction:'Complétez avec since ou for.',
   template:'I haven\'t seen my grandparents ___ a long time.',
   answer:'for',verbHint:'since/for',
   hint:'"a long time" = durée',explanation:'"For a long time" = depuis longtemps (durée).'},
  {id:'sf_1_07',type:'word-order',diffLevel:1,
   instruction:'Mettez les mots dans le bon ordre.',
   words:['She','has','worked','here','since','last','year','.'],
   answer:'She has worked here since last year.',
   hint:'Present Perfect + since + point de départ',explanation:'"Since" avec le Present Perfect pour une durée depuis un point précis.'},
  {id:'sf_1_08',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'How long have you known her? — ___ about five years.',
   options:['For','Since','During','From'],answer:'For',
   hint:'réponse à "how long" avec durée',explanation:'La réponse à "How long" avec une durée utilise "for".'},
  {id:'sf_1_09',type:'fill-blank',diffLevel:1,
   instruction:'Complétez avec since ou for.',
   template:'The shop has been closed ___ January.',
   answer:'since',verbHint:'since/for',
   hint:'"January" = mois précis',explanation:'"Since" + mois ou date spécifique.'},
  {id:'sf_1_10',type:'word-order',diffLevel:1,
   instruction:'Mettez les mots dans le bon ordre.',
   words:['I','have','had','this','phone','for','two','years','.'],
   answer:'I have had this phone for two years.',
   hint:'Present Perfect + for + durée',explanation:'"For" avec le Present Perfect pour exprimer la durée.'},
  {id:'sf_1_11',type:'fill-blank',diffLevel:1,
   instruction:'Complétez avec since ou for.',
   template:'He hasn\'t called me ___ we argued.',
   answer:'since',verbHint:'since/for',
   hint:'"since" + événement',explanation:'"Since we argued" = depuis notre dispute (événement passé).'},
  {id:'sf_1_12',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'We have been waiting ___ half an hour.',
   options:['for','since','during','while'],answer:'for',
   hint:'"half an hour" = durée',explanation:'"For" + durée (half an hour = une demi-heure).'},

  // L2 — 12 exercises
  {id:'sf_2_01',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:'Il travaille dans cette entreprise depuis dix ans.',
   answer:'He has worked in this company for ten years.',
   acceptedAnswers:['He has been working in this company for ten years.'],
   hint:'"depuis" + durée = for',explanation:'"For" + durée avec le Present Perfect.'},
  {id:'sf_2_02',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:'Elle n\'a pas dormi depuis hier soir.',
   answer:"She hasn't slept since last night.",
   acceptedAnswers:["She has not slept since last night."],
   hint:'"since" + moment précis (last night)',explanation:'"Since last night" = depuis hier soir.'},
  {id:'sf_2_03',type:'listening',diffLevel:2,
   instruction:'Écoutez et écrivez ce que vous entendez.',
   audio:"How long have you been studying French? For about six months.",
   answer:"How long have you been studying French? For about six months.",
   hint:'"How long" → réponse avec "for"',explanation:'"For about six months" répond à "how long".'},
  {id:'sf_2_04',type:'word-order',diffLevel:2,
   instruction:'Mettez les mots dans le bon ordre.',
   words:['She','has','been','ill','since','Monday','.'],
   answer:'She has been ill since Monday.',
   hint:'Present Perfect Continuous + since',explanation:'"Since Monday" = depuis lundi (point précis).'},
  {id:'sf_2_05',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:'Ils ne se sont pas parlé depuis leur dispute.',
   answer:"They haven't spoken since their argument.",
   acceptedAnswers:["They have not spoken since their argument.","They haven't talked since their argument."],
   hint:'"since their argument" = depuis leur dispute',explanation:'"Since" + événement passé pour le point de départ.'},
  {id:'sf_2_06',type:'listening',diffLevel:2,
   instruction:'Écoutez et écrivez ce que vous entendez.',
   audio:"We have known each other since we were at university.",
   answer:"We have known each other since we were at university.",
   hint:'"since" + proposition subordonnée',explanation:'"Since we were at university" = depuis l\'université.'},
  {id:'sf_2_07',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:"Ça fait longtemps que je n'ai pas vu un bon film.",
   answer:"I haven't seen a good film for a long time.",
   acceptedAnswers:["I haven't watched a good film for a long time."],
   hint:'"for a long time" = depuis longtemps',explanation:'"For a long time" exprime une longue durée.'},
  {id:'sf_2_08',type:'word-order',diffLevel:2,
   instruction:'Mettez les mots dans le bon ordre.',
   words:['He','has','not','eaten','since','breakfast','.'],
   answer:'He has not eaten since breakfast.',
   hint:'"since breakfast" = depuis le petit-déjeuner',explanation:'"Since" + repas ou moment de la journée.'},
  {id:'sf_2_09',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:'Depuis combien de temps travailles-tu ici ?',
   answer:'How long have you worked here?',
   acceptedAnswers:['How long have you been working here?'],
   hint:'"How long" + Present Perfect',explanation:'"How long have you worked?" = depuis combien de temps travailles-tu ?'},
  {id:'sf_2_10',type:'listening',diffLevel:2,
   instruction:'Écoutez et écrivez ce que vous entendez.',
   audio:"They had been married for thirty years when he passed away.",
   answer:"They had been married for thirty years when he passed away.",
   hint:'Past Perfect + for',explanation:'"Had been married for" = Past Perfect pour la durée avant un événement passé.'},
  {id:'sf_2_11',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:"Il pleut depuis ce matin.",
   answer:"It has been raining since this morning.",
   acceptedAnswers:["It has rained since this morning."],
   hint:'"since this morning" = depuis ce matin',explanation:'Present Perfect Continuous pour une action en cours depuis un moment précis.'},
  {id:'sf_2_12',type:'word-order',diffLevel:2,
   instruction:'Mettez les mots dans le bon ordre.',
   words:['I','have','not','spoken','to','him','for','months','.'],
   answer:'I have not spoken to him for months.',
   hint:'"for months" = depuis des mois',explanation:'"For months" = pendant des mois / depuis des mois.'},

  // L3 — 12 exercises
  {id:'sf_3_01',type:'error-correct',diffLevel:3,
   instruction:"Trouvez et corrigez l'erreur.",
   sentence:"I know her since three years.",
   answer:"I have known her for three years.",
   hint:'"since" avec durée est incorrect; "know" → Present Perfect',explanation:'"For" + durée. De plus, les verbes d\'état (know) utilisent le Present Perfect, pas le présent simple.'},
  {id:'sf_3_02',type:'translate-fr',diffLevel:3,
   instruction:'Traduisez en français.',
   english:"She hadn't visited her family for two years when she finally went back.",
   answer:"Elle n'avait pas rendu visite à sa famille depuis deux ans quand elle est enfin rentrée.",
   hint:'Past Perfect + for = durée avant un événement passé',explanation:'"Hadn\'t visited for two years" = Past Perfect avec "for".'},
  {id:'sf_3_03',type:'free-production',diffLevel:3,
   instruction:'Écris une phrase avec le mot donné.',
   keyword:'have known',
   hint:'ex: I have known him since we were at school.',
   explanation:'"Have known" + since/for pour exprimer une relation depuis un certain temps.'},
  {id:'sf_3_04',type:'listening-comp',diffLevel:3,
   instruction:'Écoutez et répondez à la question.',
   audio:"She has been living in Madagascar since she graduated from university five years ago.",
   question:'How long has she been living in Madagascar?',
   answer:'five years',
   acceptedAnswers:['for five years','since she graduated'],
   hint:'"since she graduated" = il y a cinq ans',explanation:'La durée est cinq ans, et le point de départ est l\'obtention du diplôme.'},
  {id:'sf_3_05',type:'error-correct',diffLevel:3,
   instruction:"Trouvez et corrigez l'erreur.",
   sentence:"They are friends since they met at school.",
   answer:"They have been friends since they met at school.",
   hint:'Present Perfect avec "since" (pas présent simple)',explanation:'Avec "since", on utilise le Present Perfect, pas le présent simple.'},
  {id:'sf_3_06',type:'translate-fr',diffLevel:3,
   instruction:'Traduisez en français.',
   english:"It has been raining for three days without stopping.",
   answer:"Il pleut depuis trois jours sans s'arrêter.",
   acceptedAnswers:["Il n'a pas cessé de pleuvoir depuis trois jours."],
   hint:'"for three days" = depuis trois jours',explanation:'Present Perfect Continuous avec "for" pour une action continue sur une période.'},
  {id:'sf_3_07',type:'free-production',diffLevel:3,
   instruction:'Écris une phrase avec le mot donné.',
   keyword:'for a long time',
   hint:'ex: We haven\'t seen each other for a long time.',
   explanation:'"For a long time" avec le Present Perfect exprime une longue durée sans préciser.'},
  {id:'sf_3_08',type:'error-correct',diffLevel:3,
   instruction:"Trouvez et corrigez l'erreur.",
   sentence:"How long are you waiting here?",
   answer:"How long have you been waiting here?",
   hint:'Present Perfect Continuous pour la durée en cours',explanation:'"How long have you been waiting?" = depuis combien de temps attends-tu ?'},
  {id:'sf_3_09',type:'listening-comp',diffLevel:3,
   instruction:'Écoutez et répondez à la question.',
   audio:"He has been working as a doctor for twenty years, ever since he finished medical school.",
   question:'When did he start working as a doctor?',
   answer:'when he finished medical school',
   acceptedAnswers:['since he finished medical school','after medical school','twenty years ago'],
   hint:'"ever since he finished" = depuis qu\'il a terminé',explanation:'"Ever since" = depuis le moment précis où quelque chose a commencé.'},
  {id:'sf_3_10',type:'translate-fr',diffLevel:3,
   instruction:'Traduisez en français.',
   english:"By the time she retired, she had been teaching for over thirty years.",
   answer:"Au moment où elle a pris sa retraite, elle enseignait depuis plus de trente ans.",
   hint:'Past Perfect Continuous + for',explanation:'"Had been teaching for" = Past Perfect Continuous pour la durée avant la retraite.'},
  {id:'sf_3_11',type:'free-production',diffLevel:3,
   instruction:'Écris une phrase avec le mot donné.',
   keyword:'since last',
   hint:'ex: I haven\'t eaten since last night.',
   explanation:'"Since last + période" (last night, last week, last year) pour un point de départ récent.'},
  {id:'sf_3_12',type:'error-correct',diffLevel:3,
   instruction:"Trouvez et corrigez l'erreur.",
   sentence:"I'm living in Antananarivo for six months.",
   answer:"I have been living in Antananarivo for six months.",
   hint:'Present Perfect Continuous (pas présent simple)',explanation:'Pour une durée continue jusqu\'au présent, on utilise le Present Perfect (Continuous).'},
];

exercises.usedTo = [
  // L1 — 12 exercises
  {id:'ut_1_01',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'She ___ play the piano when she was young.',
   options:['used to','use to','is used to','was used to'],answer:'used to',
   hint:'habitude passée qui n\'existe plus',explanation:'"Used to" exprime une habitude passée qui n\'existe plus.'},
  {id:'ut_1_02',type:'fill-blank',diffLevel:1,
   instruction:'Complétez avec "used to".',
   template:'We ___ live in a small village before moving to the city.',
   answer:'used to',verbHint:'used to',
   hint:'état passé (vivre) qui a changé',explanation:'"Used to" pour un état passé qui n\'existe plus.'},
  {id:'ut_1_03',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'___ you use to go to church every Sunday?',
   options:['Did','Were','Have','Do'],answer:'Did',
   hint:'Question avec "used to" → Did + sujet + use to',explanation:'À l\'interrogatif : Did + sujet + use to (sans -d).'},
  {id:'ut_1_04',type:'word-order',diffLevel:1,
   instruction:'Mettez les mots dans le bon ordre.',
   words:['He','used','to','work','very','hard','at','school','.'],
   answer:'He used to work very hard at school.',
   hint:'sujet + used to + verbe',explanation:'"Used to" + base verb pour une habitude passée.'},
  {id:'ut_1_05',type:'fill-blank',diffLevel:1,
   instruction:'Complétez la forme négative.',
   template:'I ___ like vegetables, but now I love them.',
   answer:"didn't use to",verbHint:'use to',
   hint:"négatif : didn't use to (sans -d)",explanation:'"Didn\'t use to" pour la forme négative des habitudes passées.'},
  {id:'ut_1_06',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'There ___ be a cinema in our town.',
   options:['used to','use to','was used to','is used to'],answer:'used to',
   hint:'état passé qui n\'existe plus (there + used to be)',explanation:'"There used to be" = il y avait (avant, plus maintenant).'},
  {id:'ut_1_07',type:'fill-blank',diffLevel:1,
   instruction:'Complétez avec la forme correcte.',
   template:'Did she ___ go to work by bus?',
   answer:'use to',verbHint:'use to',
   hint:'après "Did" → use to (sans -d)',explanation:'Après "did", on utilise "use to" sans le -d.'},
  {id:'ut_1_08',type:'word-order',diffLevel:1,
   instruction:'Mettez les mots dans le bon ordre.',
   words:["My","parents","didn't","use","to","have","a","car","."],
   answer:"My parents didn't use to have a car.",
   hint:"didn't use to + base verb",explanation:'"Didn\'t use to" = forme négative de "used to".'},
  {id:'ut_1_09',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'I am ___ to waking up early now.',
   options:['used','use','used to','use to'],answer:'used',
   hint:'"be used to" + gérondif = être habitué à',explanation:'"Be used to + -ing" = être habitué à (présent).'},
  {id:'ut_1_10',type:'fill-blank',diffLevel:1,
   instruction:'Complétez.',
   template:'They ___ walk to school every morning when they were children.',
   answer:'used to',verbHint:'used to',
   hint:'habitude quotidienne passée',explanation:'"Used to walk" = habitude passée régulière.'},
  {id:'ut_1_11',type:'word-order',diffLevel:1,
   instruction:'Mettez les mots dans le bon ordre.',
   words:['Did','you','use','to','have','a','pet','?'],
   answer:'Did you use to have a pet?',
   hint:'Did + sujet + use to + verbe ?',explanation:'Question sur une habitude passée : Did + sujet + use to.'},
  {id:'ut_1_12',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'She didn\'t ___ speak English at all before she moved abroad.',
   options:['use to','used to','used','use'],answer:'use to',
   hint:"après 'didn't' → use to",explanation:'"Didn\'t use to" (pas "didn\'t used to").'},

  // L2 — 12 exercises
  {id:'ut_2_01',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:'Elle fumait beaucoup quand elle était jeune.',
   answer:'She used to smoke a lot when she was young.',
   hint:'habitude passée',explanation:'"Used to smoke" = habitude passée.'},
  {id:'ut_2_02',type:'listening',diffLevel:2,
   instruction:'Écoutez et écrivez ce que vous entendez.',
   audio:"I used to be very shy, but now I love meeting new people.",
   answer:"I used to be very shy, but now I love meeting new people.",
   hint:'"used to be" = état passé',explanation:'"Used to be" pour un état passé qui a changé.'},
  {id:'ut_2_03',type:'word-order',diffLevel:2,
   instruction:'Mettez les mots dans le bon ordre.',
   words:['There','used','to','be','a','beautiful','park','here','.'],
   answer:'There used to be a beautiful park here.',
   hint:'"There used to be" = il y avait (avant)',explanation:'"There used to be" pour un lieu ou objet qui n\'existe plus.'},
  {id:'ut_2_04',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:"Est-ce que tu habitais à la campagne quand tu étais enfant ?",
   answer:'Did you use to live in the countryside when you were a child?',
   acceptedAnswers:['Did you use to live in the country as a child?'],
   hint:'Question : Did + sujet + use to + verbe ?',explanation:'"Did you use to" = Est-ce que tu faisais ... (avant) ?'},
  {id:'ut_2_05',type:'listening',diffLevel:2,
   instruction:'Écoutez et écrivez ce que vous entendez.',
   audio:"He didn't use to eat breakfast, but now he never skips it.",
   answer:"He didn't use to eat breakfast, but now he never skips it.",
   hint:'"didn\'t use to" = habitude passée niée',explanation:'"Didn\'t use to eat" = il ne mangeait pas (avant).'},
  {id:'ut_2_06',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:'Il y avait une grande forêt ici.',
   answer:'There used to be a large forest here.',
   acceptedAnswers:['There used to be a big forest here.'],
   hint:'"There used to be" = il y avait (plus maintenant)',explanation:'"Used to be" pour exprimer l\'existence passée d\'un lieu.'},
  {id:'ut_2_07',type:'word-order',diffLevel:2,
   instruction:'Mettez les mots dans le bon ordre.',
   words:["She","is","getting","used","to","living","alone","."],
   answer:"She is getting used to living alone.",
   hint:'"get used to" + gérondif = s\'habituer à',explanation:'"Get used to + -ing" = s\'habituer progressivement.'},
  {id:'ut_2_08',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:"Nous n'allions pas souvent au restaurant.",
   answer:"We didn't use to go to restaurants often.",
   acceptedAnswers:["We didn't use to eat out much.","We didn't use to go to restaurants very often."],
   hint:'"didn\'t use to go" = habitude passée niée',explanation:'"Didn\'t use to go" pour une habitude passée négative.'},
  {id:'ut_2_09',type:'listening',diffLevel:2,
   instruction:'Écoutez et écrivez ce que vous entendez.',
   audio:"Did she use to play a musical instrument when she was at school?",
   answer:"Did she use to play a musical instrument when she was at school?",
   hint:'"Did she use to" = question sur habitude passée',explanation:'Question : "Did + sujet + use to + verbe ?"'},
  {id:'ut_2_10',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:"Je commence à m'habituer au climat chaud.",
   answer:"I am getting used to the hot climate.",
   acceptedAnswers:["I'm getting used to the heat.","I'm getting used to the hot weather."],
   hint:'"get used to" + gérondif ou nom',explanation:'"Getting used to" = s\'habituer progressivement.'},
  {id:'ut_2_11',type:'word-order',diffLevel:2,
   instruction:'Mettez les mots dans le bon ordre.',
   words:["My","grandmother","used","to","tell","wonderful","stories","."],
   answer:"My grandmother used to tell wonderful stories.",
   hint:'"used to tell" = habitude passée',explanation:'"Used to tell" exprime une habitude passée régulière.'},
  {id:'ut_2_12',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:"Est-ce qu'il y avait une bibliothèque dans ce quartier ?",
   answer:"Did there use to be a library in this neighbourhood?",
   acceptedAnswers:["Was there used to be a library here?","Did there use to be a library in this area?"],
   hint:'"Did there use to be" = il y avait (question)',explanation:'Question avec "there used to be" : Did there use to be...?'},

  // L3 — 12 exercises
  {id:'ut_3_01',type:'error-correct',diffLevel:3,
   instruction:"Trouvez et corrigez l'erreur.",
   sentence:"She used to working as a nurse before she retired.",
   answer:"She used to work as a nurse before she retired.",
   hint:'"used to" + base verb (pas gérondif)',explanation:'"Used to" est suivi du base verb, jamais du gérondif (-ing).'},
  {id:'ut_3_02',type:'translate-fr',diffLevel:3,
   instruction:'Traduisez en français.',
   english:"I didn't use to enjoy cooking, but now I find it relaxing.",
   answer:"Je n'aimais pas cuisiner avant, mais maintenant je trouve ça relaxant.",
   hint:'"didn\'t use to enjoy" = n\'aimais pas (avant)',explanation:'"Didn\'t use to enjoy" pour une habitude passée négative.'},
  {id:'ut_3_03',type:'free-production',diffLevel:3,
   instruction:'Écris une phrase avec le mot donné.',
   keyword:'used to be',
   hint:'ex: She used to be very quiet, but now she is very outgoing.',
   explanation:'"Used to be" pour un état passé qui a changé.'},
  {id:'ut_3_04',type:'listening-comp',diffLevel:3,
   instruction:'Écoutez et répondez à la question.',
   audio:"When I was a child, I would spend hours reading comics and building models.",
   question:'Can "would" here be replaced by "used to"?',
   answer:'yes',
   acceptedAnswers:['yes, used to','yes it can','oui'],
   hint:'"would" pour habitudes passées = "used to"',explanation:'"Would" et "used to" sont interchangeables pour les habitudes passées (pas les états).'},
  {id:'ut_3_05',type:'error-correct',diffLevel:3,
   instruction:"Trouvez et corrigez l'erreur.",
   sentence:"He is used to wake up early because of his job.",
   answer:"He is used to waking up early because of his job.",
   hint:'"be used to" + gérondif (pas infinitif)',explanation:'"Be used to" est suivi d\'un gérondif (-ing), pas d\'un infinitif.'},
  {id:'ut_3_06',type:'translate-fr',diffLevel:3,
   instruction:'Traduisez en français.',
   english:"There used to be a time when people didn't have smartphones.",
   answer:"Il fut un temps où les gens n'avaient pas de smartphones.",
   acceptedAnswers:["Autrefois, les gens n'avaient pas de smartphones."],
   hint:'"There used to be a time when" = il fut un temps où',explanation:'"There used to be a time when" = structure pour parler d\'une époque révolue.'},
  {id:'ut_3_07',type:'free-production',diffLevel:3,
   instruction:'Écris une phrase avec le mot donné.',
   keyword:"didn't use to",
   hint:"ex: I didn't use to understand English, but now I speak it well.",
   explanation:'"Didn\'t use to" pour nier une habitude ou état passé.'},
  {id:'ut_3_08',type:'error-correct',diffLevel:3,
   instruction:"Trouvez et corrigez l'erreur.",
   sentence:"She would be very tall when she was young.",
   answer:"She used to be very tall when she was young.",
   hint:'"would" ne s\'utilise pas pour les états',explanation:'"Would" ne peut pas remplacer "used to" pour les états (be, have, know, etc.). Seul "used to" fonctionne.'},
  {id:'ut_3_09',type:'listening-comp',diffLevel:3,
   instruction:'Écoutez et répondez à la question.',
   audio:"My father used to walk ten kilometres to school every day. It was a very different era.",
   question:'Does this sentence imply he still walks to school?',
   answer:'no',
   acceptedAnswers:['no, he no longer does','no he doesnt anymore','non'],
   hint:'"used to" = habitude qui n\'existe plus',explanation:'"Used to" implique que l\'habitude a cessé.'},
  {id:'ut_3_10',type:'translate-fr',diffLevel:3,
   instruction:'Traduisez en français.',
   english:"The children are finally getting used to the new school routine.",
   answer:"Les enfants s'habituent enfin à la nouvelle routine scolaire.",
   hint:'"get used to" + gérondif = s\'habituer à',explanation:'"Getting used to" = processus d\'habituation progressive.'},
  {id:'ut_3_11',type:'free-production',diffLevel:3,
   instruction:'Écris une phrase avec le mot donné.',
   keyword:'be used to',
   hint:'ex: She is used to working under pressure.',
   explanation:'"Be used to + -ing" = être habitué à quelque chose (état actuel).'},
  {id:'ut_3_12',type:'error-correct',diffLevel:3,
   instruction:"Trouvez et corrigez l'erreur.",
   sentence:"Did you used to live near the sea?",
   answer:"Did you use to live near the sea?",
   hint:'après "did" → use to (sans -d)',explanation:'Dans les questions et négations avec "did", on utilise "use to" (sans -d), pas "used to".'},
];

exercises.verbsOfState = [
  // L1 — 12 exercises
  {id:'vs_1_01',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'She enjoys ___ to music every evening.',
   options:['listening','to listen','listen','listened'],answer:'listening',
   hint:'"enjoy" + gérondif (-ing)',explanation:'"Enjoy" est toujours suivi du gérondif (-ing).'},
  {id:'vs_1_02',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'He wants ___ a doctor.',
   options:['to become','becoming','become','became'],answer:'to become',
   hint:'"want" + infinitif',explanation:'"Want" est toujours suivi de l\'infinitif (to + verbe).'},
  {id:'vs_1_03',type:'fill-blank',diffLevel:1,
   instruction:'Complétez.',
   template:"I don't mind ___ late if necessary.",
   answer:'working',verbHint:'work',
   hint:'"mind" + gérondif',explanation:'"Don\'t mind" est suivi du gérondif (-ing).'},
  {id:'vs_1_04',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'She decided ___ a new job.',
   options:['to find','finding','find','found'],answer:'to find',
   hint:'"decide" + infinitif',explanation:'"Decide" est suivi de l\'infinitif.'},
  {id:'vs_1_05',type:'fill-blank',diffLevel:1,
   instruction:'Complétez.',
   template:'I love ___ football on weekends.',
   answer:'playing',verbHint:'play',
   hint:'"love" + gérondif OU infinitif',explanation:'"Love" peut être suivi du gérondif ou de l\'infinitif.'},
  {id:'vs_1_06',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'They finished ___ the project on time.',
   options:['completing','to complete','complete','completed'],answer:'completing',
   hint:'"finish" + gérondif',explanation:'"Finish" est suivi du gérondif (-ing).'},
  {id:'vs_1_07',type:'fill-blank',diffLevel:1,
   instruction:'Complétez.',
   template:'She hopes ___ Paris one day.',
   answer:'to visit',verbHint:'visit',
   hint:'"hope" + infinitif',explanation:'"Hope" est suivi de l\'infinitif (to + verbe).'},
  {id:'vs_1_08',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'He stopped ___ (and never started again).',
   options:['smoking','to smoke','smoke','smoked'],answer:'smoking',
   hint:'"stop + -ing" = arrêter définitivement',explanation:'"Stop + -ing" = arrêter de faire quelque chose.'},
  {id:'vs_1_09',type:'fill-blank',diffLevel:1,
   instruction:'Complétez.',
   template:'I hate ___ in queues.',
   answer:'waiting',verbHint:'wait',
   hint:'"hate" + gérondif OU infinitif',explanation:'"Hate" peut être suivi du gérondif ou de l\'infinitif.'},
  {id:'vs_1_10',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'She promised ___ on time.',
   options:['to arrive','arriving','arrive','arrived'],answer:'to arrive',
   hint:'"promise" + infinitif',explanation:'"Promise" est suivi de l\'infinitif.'},
  {id:'vs_1_11',type:'word-order',diffLevel:1,
   instruction:'Mettez les mots dans le bon ordre.',
   words:['He','avoids','eating','fast','food','whenever','possible','.'],
   answer:'He avoids eating fast food whenever possible.',
   hint:'"avoid" + gérondif',explanation:'"Avoid" est suivi du gérondif (-ing).'},
  {id:'vs_1_12',type:'fill-blank',diffLevel:1,
   instruction:'Complétez.',
   template:'Do you prefer ___ at home or going out?',
   answer:'staying',verbHint:'stay',
   hint:'"prefer" + gérondif OU infinitif',explanation:'"Prefer" peut être suivi du gérondif ou de l\'infinitif.'},

  // L2 — 12 exercises
  {id:'vs_2_01',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:'Elle évite de conduire la nuit.',
   answer:'She avoids driving at night.',
   hint:'"avoid" + gérondif',explanation:'"Avoid" + gérondif (-ing).'},
  {id:'vs_2_02',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:'Il a arrêté de fumer il y a deux ans.',
   answer:'He stopped smoking two years ago.',
   hint:'"stop + -ing" = arrêter de',explanation:'"Stop smoking" = arrêter de fumer (définitivement).'},
  {id:'vs_2_03',type:'listening',diffLevel:2,
   instruction:'Écoutez et écrivez ce que vous entendez.',
   audio:"I enjoy cooking for my family on Sundays.",
   answer:"I enjoy cooking for my family on Sundays.",
   hint:'"enjoy" + gérondif',explanation:'"Enjoy cooking" : "enjoy" exige le gérondif.'},
  {id:'vs_2_04',type:'word-order',diffLevel:2,
   instruction:'Mettez les mots dans le bon ordre.',
   words:['She','keeps','making','the','same','mistakes','.'],
   answer:'She keeps making the same mistakes.',
   hint:'"keep" + gérondif = continuer à',explanation:'"Keep + -ing" = continuer à faire quelque chose.'},
  {id:'vs_2_05',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:'Il a oublié d\'envoyer le rapport.',
   answer:'He forgot to send the report.',
   hint:'"forget + infinitif" = oublier de faire',explanation:'"Forget + infinitif" = oublier de faire quelque chose (dans le futur).'},
  {id:'vs_2_06',type:'listening',diffLevel:2,
   instruction:'Écoutez et écrivez ce que vous entendez.',
   audio:"Would you mind closing the window? It's quite cold.",
   answer:"Would you mind closing the window? It's quite cold.",
   hint:'"mind" + gérondif dans les requêtes polies',explanation:'"Would you mind + -ing?" = cela vous dérangerait-il de...?'},
  {id:'vs_2_07',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:"Je me souviens de l'avoir rencontré à Paris.",
   answer:'I remember meeting him in Paris.',
   acceptedAnswers:['I remember meeting her in Paris.'],
   hint:'"remember + -ing" = se souvenir d\'avoir fait',explanation:'"Remember + -ing" = se souvenir d\'une action passée.'},
  {id:'vs_2_08',type:'word-order',diffLevel:2,
   instruction:'Mettez les mots dans le bon ordre.',
   words:['I','prefer','walking','to','taking','the','bus','.'],
   answer:'I prefer walking to taking the bus.',
   hint:'"prefer + -ing + to + -ing" = préférer',explanation:'"Prefer A to B" : A et B sont tous deux des gérondifs.'},
  {id:'vs_2_09',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:"Il s'est arrêté pour acheter de l'eau.",
   answer:'He stopped to buy water.',
   hint:'"stop + infinitif" = s\'arrêter pour faire',explanation:'"Stop + infinitif" = s\'arrêter afin de faire quelque chose.'},
  {id:'vs_2_10',type:'listening',diffLevel:2,
   instruction:'Écoutez et écrivez ce que vous entendez.',
   audio:"She needs to study harder if she wants to pass the exam.",
   answer:"She needs to study harder if she wants to pass the exam.",
   hint:'"need" et "want" + infinitif',explanation:'"Need to" et "want to" sont suivis de l\'infinitif.'},
  {id:'vs_2_11',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:"Tu t'es souvenu de fermer la porte ?",
   answer:'Did you remember to close the door?',
   acceptedAnswers:['Did you remember to lock the door?','Did you remember to shut the door?'],
   hint:'"remember + infinitif" = penser à faire',explanation:'"Remember + infinitif" = ne pas oublier de faire.'},
  {id:'vs_2_12',type:'word-order',diffLevel:2,
   instruction:'Mettez les mots dans le bon ordre.',
   words:["He","decided","to","change","careers","after","ten","years","."],
   answer:"He decided to change careers after ten years.",
   hint:'"decide" + infinitif',explanation:'"Decide to + base verb" = décider de faire quelque chose.'},

  // L3 — 12 exercises
  {id:'vs_3_01',type:'error-correct',diffLevel:3,
   instruction:"Trouvez et corrigez l'erreur.",
   sentence:'She enjoys to read historical novels.',
   answer:'She enjoys reading historical novels.',
   hint:'"enjoy" + gérondif (pas infinitif)',explanation:'"Enjoy" est obligatoirement suivi du gérondif (-ing).'},
  {id:'vs_3_02',type:'translate-fr',diffLevel:3,
   instruction:'Traduisez en français.',
   english:"He stopped to talk to her, but she was in a hurry.",
   answer:"Il s'est arrêté pour lui parler, mais elle était pressée.",
   hint:'"stopped to talk" = s\'arrêter pour parler',explanation:'"Stop + infinitif" = interrompre une activité pour faire autre chose.'},
  {id:'vs_3_03',type:'free-production',diffLevel:3,
   instruction:'Écris une phrase avec le mot donné.',
   keyword:'enjoy',
   hint:'ex: I enjoy spending time with my family on weekends.',
   explanation:'"Enjoy" + gérondif pour exprimer un plaisir.'},
  {id:'vs_3_04',type:'listening-comp',diffLevel:3,
   instruction:'Écoutez et répondez à la question.',
   audio:'She remembered locking the door, so she did not go back.',
   question:'Does she need to go back to lock the door?',
   answer:'no',
   acceptedAnswers:['no she doesnt','no, she already locked it','non'],
   hint:'"remember + -ing" = se souvenir d\'avoir déjà fait',explanation:'"Remember locking" = elle se souvient d\'avoir déjà fermé à clé.'},
  {id:'vs_3_05',type:'error-correct',diffLevel:3,
   instruction:"Trouvez et corrigez l'erreur.",
   sentence:'I suggest to take the train instead of the bus.',
   answer:'I suggest taking the train instead of the bus.',
   hint:'"suggest" + gérondif',explanation:'"Suggest" est toujours suivi du gérondif (-ing).'},
  {id:'vs_3_06',type:'translate-fr',diffLevel:3,
   instruction:'Traduisez en français.',
   english:"I regret not having studied harder when I was at school.",
   answer:"Je regrette de ne pas avoir étudié davantage quand j'étais à l'école.",
   hint:'"regret + -ing" = regretter d\'avoir fait',explanation:'"Regret + -ing" = regretter une action passée.'},
  {id:'vs_3_07',type:'free-production',diffLevel:3,
   instruction:'Écris une phrase avec le mot donné.',
   keyword:"don't mind",
   hint:"ex: I don't mind helping you with your homework.",
   explanation:'"Don\'t mind + -ing" = ne pas déranger de faire quelque chose.'},
  {id:'vs_3_08',type:'error-correct',diffLevel:3,
   instruction:"Trouvez et corrigez l'erreur.",
   sentence:'He tried studying all night, but the exam was very hard.',
   answer:'He tried studying all night, but the exam was very hard.',
   hint:'Cette phrase est correcte !',explanation:'"Try + -ing" = essayer comme méthode. La phrase est correcte.'},
  {id:'vs_3_09',type:'listening-comp',diffLevel:3,
   instruction:'Écoutez et répondez à la question.',
   audio:'He tried to open the jar but he could not manage it.',
   question:'Did he succeed in opening the jar?',
   answer:'no',
   acceptedAnswers:['no he didnt','no he couldnt','non'],
   hint:'"try + infinitif" = tenter (sans certitude de succès)',explanation:'"Try + infinitif" = faire un effort pour accomplir quelque chose.'},
  {id:'vs_3_10',type:'translate-fr',diffLevel:3,
   instruction:'Traduisez en français.',
   english:'I considered changing jobs, but in the end I decided to stay.',
   answer:"J'ai envisagé de changer d'emploi, mais finalement j'ai décidé de rester.",
   hint:'"consider + -ing" = envisager de',explanation:'"Consider + -ing" = envisager, "decide + infinitif" = décider.'},
  {id:'vs_3_11',type:'free-production',diffLevel:3,
   instruction:'Écris une phrase avec le mot donné.',
   keyword:'keep',
   hint:'ex: He keeps interrupting me when I speak.',
   explanation:'"Keep + -ing" = continuer à faire quelque chose de manière répétée.'},
  {id:'vs_3_12',type:'error-correct',diffLevel:3,
   instruction:"Trouvez et corrigez l'erreur.",
   sentence:'She managed finishing the report before the deadline.',
   answer:'She managed to finish the report before the deadline.',
   hint:'"manage" + infinitif',explanation:'"Manage" est toujours suivi de l\'infinitif (to + verbe).'},
];

exercises.adjectives = [
  // L1 — 12 exercises
  {id:'adj_1_01',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'She has ___ hair.',
   options:['long black','black long','long blacks','blacks long'],answer:'long black',
   hint:'taille avant couleur dans l\'ordre des adjectifs',explanation:'L\'ordre standard : taille → couleur (long black hair).'},
  {id:'adj_1_02',type:'fill-blank',diffLevel:1,
   instruction:'Complétez avec this, that, these ou those.',
   template:'Look at ___ stars in the sky! (loin, pluriel)',
   answer:'those',verbHint:'this/that/these/those',
   hint:'"those" = loin + pluriel',explanation:'"Those" = démonstratif pluriel pour des objets éloignés.'},
  {id:'adj_1_03',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'___ is my book. (ce livre-ci)',
   options:['This','That','These','Those'],answer:'This',
   hint:'"this" = proche + singulier',explanation:'"This" = démonstratif singulier pour un objet proche.'},
  {id:'adj_1_04',type:'word-order',diffLevel:1,
   instruction:'Mettez les mots dans le bon ordre.',
   words:['She','is','a','tall','and','beautiful','woman','.'],
   answer:'She is a tall and beautiful woman.',
   hint:'adjectifs avant le nom',explanation:'En anglais, les adjectifs se placent avant le nom.'},
  {id:'adj_1_05',type:'fill-blank',diffLevel:1,
   instruction:'Complétez avec l\'adjectif correct.',
   template:'The opposite of "happy" is ___.',
   answer:'sad',verbHint:'happy/sad',
   hint:'heureux ↔ triste',explanation:'"Sad" est le contraire de "happy".'},
  {id:'adj_1_06',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'___ shoes are more comfortable than mine. (loin, pluriel)',
   options:['Those','These','This','That'],answer:'Those',
   hint:'"those" = loin + pluriel',explanation:'"Those" pour des objets éloignés au pluriel.'},
  {id:'adj_1_07',type:'fill-blank',diffLevel:1,
   instruction:'Complétez.',
   template:'He drives a ___ red car.',
   answer:'big',verbHint:'big/small',
   hint:'taille avant couleur',explanation:'L\'ordre : taille (big) avant couleur (red).'},
  {id:'adj_1_08',type:'word-order',diffLevel:1,
   instruction:'Mettez les mots dans le bon ordre.',
   words:['I','have','a','new','blue','French','bicycle','.'],
   answer:'I have a new blue French bicycle.',
   hint:'âge → couleur → origine',explanation:'Ordre : âge (new) → couleur (blue) → origine (French).'},
  {id:'adj_1_09',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'The cat is very ___.',
   options:['cutely','cute','cutes','cutest'],answer:'cute',
   hint:'adjectif après "be" (pas d\'adverbe)',explanation:'Après "be", on utilise un adjectif (cute), pas un adverbe (cutely).'},
  {id:'adj_1_10',type:'fill-blank',diffLevel:1,
   instruction:'Complétez avec l\'adjectif contraire.',
   template:'This bag is cheap but ___ one is expensive.',
   answer:'that',verbHint:'this/that',
   hint:'"that" = démonstratif singulier pour objet éloigné',explanation:'"That" = démonstratif pour un objet plus éloigné.'},
  {id:'adj_1_11',type:'word-order',diffLevel:1,
   instruction:'Mettez les mots dans le bon ordre.',
   words:['These','are','very','interesting','books','.'],
   answer:'These are very interesting books.',
   hint:'"these" = proche + pluriel',explanation:'"These" + pluriel pour des objets proches.'},
  {id:'adj_1_12',type:'multiple-choice',diffLevel:1,
   instruction:'Choisissez la bonne réponse.',
   question:'She wore a ___ dress to the party.',
   options:['beautiful long red','long beautiful red','beautiful red long','red long beautiful'],answer:'beautiful long red',
   hint:'opinion → taille → couleur',explanation:'Ordre : opinion (beautiful) → taille (long) → couleur (red).'},

  // L2 — 12 exercises
  {id:'adj_2_01',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:'Elle porte une longue robe noire élégante.',
   answer:'She is wearing an elegant long black dress.',
   acceptedAnswers:['She wears an elegant long black dress.'],
   hint:'opinion → taille → couleur',explanation:'Ordre correct : opinion (elegant) → taille (long) → couleur (black).'},
  {id:'adj_2_02',type:'listening',diffLevel:2,
   instruction:'Écoutez et écrivez ce que vous entendez.',
   audio:"Those old wooden houses near the river are absolutely beautiful.",
   answer:"Those old wooden houses near the river are absolutely beautiful.",
   hint:'ordre : âge → matière → emplacement → opinion',explanation:'"Those old wooden houses" : âge (old) → matière (wooden).'},
  {id:'adj_2_03',type:'word-order',diffLevel:2,
   instruction:'Mettez les mots dans le bon ordre.',
   words:['It','was','a','dark','and','stormy','night','.'],
   answer:'It was a dark and stormy night.',
   hint:'"and" pour coordonner deux adjectifs du même type',explanation:'"And" coordonne deux adjectifs. Ordre libre quand ils sont du même type.'},
  {id:'adj_2_04',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:'Ce jeune homme est très intelligent.',
   answer:'This young man is very intelligent.',
   hint:'"this" = proche + singulier',explanation:'"This" démonstratif pour un sujet proche. Adjectifs : young (âge), intelligent (opinion).'},
  {id:'adj_2_05',type:'listening',diffLevel:2,
   instruction:'Écoutez et écrivez ce que vous entendez.',
   audio:"That small round Japanese table in the corner is my favourite.",
   answer:"That small round Japanese table in the corner is my favourite.",
   hint:'taille → forme → origine',explanation:'"Small round Japanese" : taille → forme → origine.'},
  {id:'adj_2_06',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:'Je préfère ces chaussures-là à celles-ci.',
   answer:'I prefer those shoes to these.',
   acceptedAnswers:['I prefer those shoes to these ones.'],
   hint:'"those" (loin) vs "these" (proche)',explanation:'"Those" pour les éloignées, "these" pour les proches.'},
  {id:'adj_2_07',type:'word-order',diffLevel:2,
   instruction:'Mettez les mots dans le bon ordre.',
   words:['She','speaks','in','a','very','quiet','and','calm','voice','.'],
   answer:'She speaks in a very quiet and calm voice.',
   hint:'adjectifs coordonnés avec "and"',explanation:'"Quiet and calm" : deux adjectifs de même nature coordonnés.'},
  {id:'adj_2_08',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:'Il est fatigué mais heureux.',
   answer:'He is tired but happy.',
   hint:'deux adjectifs après "be" + "but"',explanation:'Deux adjectifs après "be" coordonnés par "but".'},
  {id:'adj_2_09',type:'listening',diffLevel:2,
   instruction:'Écoutez et écrivez ce que vous entendez.',
   audio:"She runs quickly but she is a slow walker.",
   answer:"She runs quickly but she is a slow walker.",
   hint:'"quickly" (adverbe) vs "slow" (adjectif)',explanation:'"Runs quickly" (adverbe) vs "a slow walker" (adjectif + nom).'},
  {id:'adj_2_10',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:'Ce vieux livre français est très précieux.',
   answer:'This old French book is very precious.',
   acceptedAnswers:['This old French book is very valuable.'],
   hint:'âge → origine + adjectif après "be"',explanation:'"Old French" : âge → origine. "Precious" après "is".'},
  {id:'adj_2_11',type:'word-order',diffLevel:2,
   instruction:'Mettez les mots dans le bon ordre.',
   words:["That","was","a","wonderful","performance","by","the","young","musicians","."],
   answer:"That was a wonderful performance by the young musicians.",
   hint:'"wonderful" (opinion) avant "young" (âge)',explanation:'"Wonderful" (opinion/évaluation) en premier.'},
  {id:'adj_2_12',type:'translate',diffLevel:2,
   instruction:'Traduisez en anglais.',
   french:'Ces grandes maisons blanches sont toutes modernes.',
   answer:'These big white houses are all modern.',
   acceptedAnswers:['These large white houses are all modern.'],
   hint:'taille → couleur + adjectif prédicat',explanation:'"Big white" : taille → couleur. "Modern" est attribut après "are".'},

  // L3 — 12 exercises
  {id:'adj_3_01',type:'error-correct',diffLevel:3,
   instruction:"Trouvez et corrigez l'erreur.",
   sentence:'She is wearing a red small Italian scarf.',
   answer:'She is wearing a small red Italian scarf.',
   hint:'taille → couleur → origine',explanation:'L\'ordre correct : taille (small) → couleur (red) → origine (Italian).'},
  {id:'adj_3_02',type:'translate-fr',diffLevel:3,
   instruction:'Traduisez en français.',
   english:'That beautiful old stone farmhouse belongs to my grandparents.',
   answer:"Cette belle vieille ferme en pierre appartient à mes grands-parents.",
   hint:'opinion → âge → matière',explanation:'"Beautiful old stone" : opinion → âge → matière.'},
  {id:'adj_3_03',type:'free-production',diffLevel:3,
   instruction:'Écris une phrase avec le mot donné.',
   keyword:'those',
   hint:'ex: Those tall mountains in the north are breathtaking.',
   explanation:'"Those" = démonstratif pluriel pour des éléments éloignés.'},
  {id:'adj_3_04',type:'listening-comp',diffLevel:3,
   instruction:'Écoutez et répondez à la question.',
   audio:'He drove a shiny new German sports car.',
   question:'What is the correct order of adjectives?',
   answer:'opinion, age, origin, type',
   acceptedAnswers:['shiny new german sports','opinion age origin type','shiny new German sports'],
   hint:'opinion → âge → origine → type',explanation:'Ordre : opinion (shiny) → âge (new) → origine (German) → type (sports).'},
  {id:'adj_3_05',type:'error-correct',diffLevel:3,
   instruction:"Trouvez et corrigez l'erreur.",
   sentence:'She runs very quick.',
   answer:'She runs very quickly.',
   hint:'"quickly" = adverbe (modifie le verbe)',explanation:'Pour modifier un verbe, on utilise un adverbe (quickly), pas un adjectif (quick).'},
  {id:'adj_3_06',type:'translate-fr',diffLevel:3,
   instruction:'Traduisez en français.',
   english:'The exhausted but determined athlete crossed the finish line.',
   answer:"L'athlète épuisé mais déterminé a franchi la ligne d'arrivée.",
   hint:'"exhausted but determined" = deux adjectifs épithètes',explanation:'Deux adjectifs épithètes coordonnés par "but" devant le nom.'},
  {id:'adj_3_07',type:'free-production',diffLevel:3,
   instruction:'Écris une phrase décrivant un objet avec 3 adjectifs dans le bon ordre.',
   keyword:'adjectives order',
   hint:'ex: I bought a lovely little old Italian clock.',
   explanation:'Ordre : opinion → taille → âge → forme → couleur → origine → matière.'},
  {id:'adj_3_08',type:'error-correct',diffLevel:3,
   instruction:"Trouvez et corrigez l'erreur.",
   sentence:'This is an interested book about ancient history.',
   answer:'This is an interesting book about ancient history.',
   hint:'"interesting" (qualifie le livre) ≠ "interested" (qualifie une personne)',explanation:'"Interesting" qualifie quelque chose. "Interested" qualifie une personne qui s\'intéresse.'},
  {id:'adj_3_09',type:'listening-comp',diffLevel:3,
   instruction:'Écoutez et répondez à la question.',
   audio:'She felt bored during the long meeting.',
   question:'Is "bored" used as an attributive or predicative adjective here?',
   answer:'predicative',
   acceptedAnswers:['predicative adjective','attribut du sujet','attributive'],
   hint:'après "felt" = attribut du sujet',explanation:'"Bored" après "felt" est un adjectif attribut (predicative). Attributif = avant le nom.'},
  {id:'adj_3_10',type:'translate-fr',diffLevel:3,
   instruction:'Traduisez en français.',
   english:'She has a charming little old white wooden house in the countryside.',
   answer:"Elle a une charmante petite vieille maison blanche en bois à la campagne.",
   hint:'opinion → taille → âge → couleur → matière',explanation:'Ordre complet : opinion (charming) → taille (little) → âge (old) → couleur (white) → matière (wooden).'},
  {id:'adj_3_11',type:'free-production',diffLevel:3,
   instruction:'Écris une phrase avec le mot donné.',
   keyword:'this',
   hint:'ex: This ancient red Chinese vase is incredibly rare.',
   explanation:'"This" + nom + adjectifs en ordre correct.'},
  {id:'adj_3_12',type:'error-correct',diffLevel:3,
   instruction:"Trouvez et corrigez l'erreur.",
   sentence:'He looked at me in a suspicious manner strange.',
   answer:'He looked at me in a strange suspicious manner.',
   hint:'ordre : opinion/évaluation → caractère',explanation:'"Strange suspicious manner" : l\'évaluation (strange) avant le caractère (suspicious).'},
];
"""

# ─────────────────────────────────────────────────────────────────────────────
# Apply changes
# ─────────────────────────────────────────────────────────────────────────────

# ── theory.js ────────────────────────────────────────────────────────────────
with open(THEORY_PATH, encoding='utf-8') as f:
    theory_src = f.read()

# 1. Insert new theory sections before `export const theoryTopics`
THEORY_INSERT_MARKER = 'export const theoryTopics'
assert THEORY_INSERT_MARKER in theory_src, 'Marker not found in theory.js'
theory_src = theory_src.replace(THEORY_INSERT_MARKER,
    NEW_THEORY + '\n' + THEORY_INSERT_MARKER)

# 2. Add new theoryTopics entries before the closing `];`
TOPICS_CLOSE = '];'
# Find the theoryTopics section specifically
idx_topics = theory_src.find('export const theoryTopics')
idx_close = theory_src.find('];', idx_topics)
theory_src = theory_src[:idx_close] + NEW_THEORY_TOPICS + '\n' + theory_src[idx_close:]

# 3. Add new Boky chapters before the closing `];` of malgasyManual
idx_boky_start = theory_src.find('export const malgasyManual')
# find the last `];` after malgasyManual
idx_boky_close = theory_src.rfind('];\n\n// ─── Topics list')
theory_src = theory_src[:idx_boky_close] + NEW_BOKY + '\n' + theory_src[idx_boky_close:]

with open(THEORY_PATH, 'w', encoding='utf-8') as f:
    f.write(theory_src)
print('theory.js updated.')

# ── exercises.js ─────────────────────────────────────────────────────────────
with open(EXERCISES_PATH, encoding='utf-8') as f:
    ex_src = f.read()

INSERT_MARKER = 'export function getAllExercises()'
assert INSERT_MARKER in ex_src
ex_src = ex_src[:ex_src.index(INSERT_MARKER)] + NEW_EXERCISES + '\n' + ex_src[ex_src.index(INSERT_MARKER):]

with open(EXERCISES_PATH, 'w', encoding='utf-8') as f:
    f.write(ex_src)
print('exercises.js updated.')
print('Done: sinceFor, usedTo, verbsOfState, adjectives sections added.')
